runtime:
  cache_dir: ./.cache/antora

site:
  title: Knative Tutorial
  url: https://redhat-developer-demos.github.io/knative-tutorial
  start_page: knative-tutorial::index.adoc

content:
  sources:
    - url: git@github.com:redhat-developer-demos/knative-tutorial.git
      tags: v1.13.0
      branches: []
      start_path: documentation
asciidoc:
  attributes:
    tutorial-namespace: knativetutorial
    branch: v1.13.0
    workshop-domain: guru.devx.red
    minikube-version:  v1.17.1
    openshift-version: v4.6
    kubernetes-version: v1.19.0
    knative-version: v0.19.0
    knative-serving-version: v0.19.0
    net-kourier-version: v0.19.0
    knative-eventing-version: v0.19.2
    knative-sources-version: v0.19.0
    kn-client-version: v0.19.1
    camel-source-version: v0.19.0
    kafka-source-version: v0.19.3
    kamel-version: 1.3.1
    kubernetes-cli: kubectl
    release-version: master
    page-pagination: true
    openshift-console-url: https://console-openshift-console.apps.example.com
    etherpad-url: http://example.com
  extensions:
    - ./lib/remote-include-processor.js
    - ./lib/tab-block.js
ui:
  bundle:
    url: https://github.com/redhat-developer-demos/rhd-tutorial-ui/releases/download/v0.1.9/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  dir: ./gh-pages
