= Build Template
include::_attributes.adoc[]

The raw builds like what we did in xref:ROOT:05-build/build.adoc[previous chapter] has some disadvantages:

 * No reusability 
 * Hard coding of build parameters 
 * Inability to make builds and services in synchronous i.e. services are deployed only after the related build is complete

One of the solutions to these problems is **Build Templates**.

Similarly to the build spec, the Knative build template spec and the Knative service spec needs some customizations before being applied.

[#build-template-prerequisite]
== Prerequisite 
include::partial$prereq-cli.adoc[]

[IMPORTANT]
====
* Please ensure that you have xref:ROOT:05-build/build.adoc#build-registry-account[container registry account] created.

* xref:ROOT:05-build/build.adoc#build-set-env[Build environment variables] has been configured.

* Pre-requisite xref:ROOT:05-build/build.adoc#build-apply-prereq-resources[kubernetes resources] have been created and applied.
====

[#build-template-template]
=== Knative build template 

[source,bash,subs="+macros,+attributes"]
----
cd $TUTORIAL_HOME/{build-repo}/knative
----

For this chapters build template demos, we will be using the following Knative build template that will use maven to build the Java application. The build template leverages Kaniko to build and push the container image based on the Java application built using maven.

[.text-center]
.maven-build-template.yaml
[source,yaml,linenums]
----
apiVersion: build.knative.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: build-java-maven
spec:
  parameters: #<1>
    - description: |
        The name of the image to push.
      name: IMAGE
    - description: |
        The context directory from where to run the build.
      name: CONTEXT_DIR
  steps:
    - args:
        - "/usr/local/bin/buildah.sh"
      env:
        - name: WORK_DIR
          value: /workspace/${CONTEXT_DIR}
        - name: DESTINATION_NAME
          value: ${IMAGE}
        # uncomment this if you have MAVEN_MIRROR thats is reachable from your kube cluster
        # speeds up the builds - the example below uses Nexus repo manager installed in host machine
        # - name: MAVEN_MIRROR_URL
        #  value: $http://192.168.64.1:8081/nexus/content/groups/public
      image: quay.io/rhdevelopers/quarkus-java-builder
      name: build-and-push
      # needed for buildah builds to be running as containers
      securityContext:
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
        - mountPath: /root/.m2
          name: m2-cache
        - mountPath: /var/lib/containers
          name: container-storage
      workingDir: /workspace/${CONTEXT_DIR}
  timeout: 60m
  volumes:
    - name: m2-cache
      persistentVolumeClaim:
        claimName: m2-cache
    - name: container-storage
      hostPath:
        path: /var/lib/containers
----

<1> The build template does not have any hard-coded values, *the dynamic values could be passed using **parameters** of the template.

The build done by the build steps of the template is exactly same like what was done by xref:ROOT:05-build/build.adoc#build-create-build[raw build], but templates gives flexibility and ease of configuration via parameters. The template step(s) modifications are transparent to the consumers (the builds inheriting the template), the builds using the template will automatically inherit the modified steps.

[#build-template-edit-service]
=== Edit Knative service

Run the following command to create the knative service that will use the image created by the Knative build template we defined earlier.

[source,bash,subs="+macros,+attributes",linenums]
----
pass:[ sed -i "s~\$contextDir~${CONTEXT_DIR}~g; s~\$sourceRepoUrl~${SOURCE_REPO_URL}~g; s~\$sourceRevision~${SOURCE_REVISION}~g; s~\$destinationImageName~${DESTINATION_IMAGE_NAME}~g" service-with-build-template.yaml ]
----

Running the above command will result in the following knative service file:

[.text-center]
.service-with-build-template.yaml
[source,yaml,linenums]
----
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: event-greeter
spec:
  runLatest:
    configuration:
      build:
        apiVersion: build.knative.dev/v1alpha1
        kind: Build
        spec:
          serviceAccountName: build-bot
          source:
            git:
              revision: v0.0.2 # <1>
              url: https://github.com/redhat-developer-demos/knative-tutorial-event-greeter.git
          template:
            arguments: # <2>
              - name: IMAGE
                value: docker.io/demo/event-greeter:0.0.2
              - name: CONTEXT_DIR
                value: java/quarkus
            name: build-java-maven # <3>
          timeout: 20m
      revisionTemplate:
        metadata:
          labels:
            app: event-greeter
        spec:
          container:
            image: docker.io/kameshsampath/event-greeter:0.0.2
----

<1> Using another branch from the sources, just to differentiate the image produced by this build
<2> Passing the parameters required by the build template, not passing the required parameters will result in build validation failure
<3> The name of the build template to use

NOTE: The above yaml has dummy values for IMAGE, CONTEXT_DIR etc., the actual values will be based on what you set in `setenv.sh`. For more details check the  xref:ROOT:05-build/build.adoc#build-set-env[Build environment variables] section.

[#build-template-apply-resources]
=== Apply resources

As we have already xref:ROOT:05-build/build.adoc#build-apply-prereq-resources[applied the pre-req] resources, lets jump straight to applying the template and service.

[#build-template-create-template]
== Create build template

[source,bash,subs="+macros,+attributes"]
----
kubectl apply -n knativetutorial -f maven-build-template.yaml
----

.(OR)

[source,bash,subs="+macros,+attributes"]
----
oc apply -n knativetutorial -f maven-build-template.yaml
----

[#build-see-what-you-have-deployed]
=== See what you have deployed

[#build-show-knative-build-templates]
==== build templates
include::partial$knative-objects.adoc[tag=knative-build-templates]

[#build-deploy-service-build-template]
== Deploy service using Build Template

With build templates the automatic build may not be triggered unless and until some service or build referring to the template gets created.

Run the following commands to deploy the service:

[source,bash,subs="+macros,+attributes"]
----
kubectl apply -n knativetutorial -f service-with-build-template.yaml
----

.(OR)

[source,bash,subs="+macros,+attributes"]
----
oc apply -n knativetutorial -f service-with-build-template.yaml
----


You can also xref:ROOT:05-build/build.adoc#build-watching-logs[watch the logs] of the build triggered with the service deployment.

After successful deployment of the service we should see a kubernetes deployment like `event-greeter-8fvqf-deployment` available.

[#build-template-invoke-service]
== Invoke Service

:k8s-env: minikube
:k8s-cli: kubectl
include::ROOT:partial$invoke-service.adoc[tag=env]

.(OR)

:k8s-env: minishift
:k8s-cli: oc
include::ROOT:partial$invoke-service.adoc[tag=env]

[source,bash,subs="+macros,+attributes",linenums]
----
curl -H "Host:event-greeter.knativetutorial.example.com" $IP_ADDRESS \
   -H "Content-Type: application/json" \
   -d '{"message": "test message"}'
----

.(OR)

[source,bash,subs="+macros,+attributes",linenums]
----
http POST $IP_ADDRESS \
  'Host:event-greeter.knativetutorial.example.com'  \
   message="test message"
----

The above command should return an response like:

[source,json]
----
{
    "host": "Event  greeter => 'event-greeter-rz7lz-pod-938e74' : 1",
    "message": "test message",
    "time": "15:54:45"
}
----

[#build-template-cleanup]
=== Cleanup

[source,bash,subs="+macros,+attributes",linenums]
----
kubectl -n knativetutorial delete services.serving.knative.dev event-greeter
kubectl -n knativetutorial delete buildtemplates.build.knative.dev build-java-maven
----

.(OR)

[source,bash,subs="+macros,+attributes",linenums]
----
oc -n knativetutorial delete services.serving.knative.dev event-greeter
oc -n knativetutorial delete buildtemplates.build.knative.dev build-java-maven
----

NOTE: You can also delete xref:ROOT:05-build/build.adoc#build-apply-prereq-resources[pre-req resources] that were created if you don't need them anymore.
