= Build
include::_attributes.adoc[]

At the end of this chapter you will be able to:

* Define build
* Define build templates
* How to make service use builds for building container images a.k.a source-to -url

[#build-prerequisite]
== Prerequisite 
include::partial$prereq-cli.adoc[]

[#build-registry-account]
[IMPORTANT]
====
Its required that you have container registry account which is needed during the exercises to push the built container images. 

You can get one for free at https://hub.docker.com[Docker Hub]
====

As the Knative build and build template specs need some customizations, such as creating a secret with your container registry credentials; we need to set the following environment variables before running the other commands of the section.

include::partial$build-nav-folder.adoc[]

[#build-set-env]
== Configure build environment variables

[#copy-set-env-sh]
[source,bash,subs="+macros,+attributes"]
----
cp link:{github-repo}/{build-repo}/knative/setenv.sh.example[setenv.sh.example] setenv.sh
----
copyToClipboard::copy-set-env-sh[]

Update the following environment variables as per your needs and customizations. 

include::partial$build-env-vars.adoc[]

[#source-set-env-sh]
[source,bash,subs="+macros,+attributes",linenums]
----
source $TUTORIAL_HOME/{build-repo}/knative/setenv.sh
----
copyToClipboard::source-set-env-sh[]

[#build-edit-cr-secret]
== Edit Container Registry Secret
A container registry secret is required for the build to authenticate with the container registry, so that it can build and push the image to the registry.

[#build-run-edit-cr-secret]
[source,bash,subs="+macros,+attributes",linenums]
----
yq w -i container-registry-secret.yaml 'metadata.annotations.[build.knative.dev/docker-0]' pass:[$REGISTRY_URL] && \
yq w -i container-registry-secret.yaml stringData.username pass:[$REGISTRY_USERNAME] && \
yq w -i container-registry-secret.yaml stringData.password pass:[$REGISTRY_PASSWORD]
----
copyToClipboard::build-run-edit-cr-secret[]

The above command will generate a Kubernetes secret as shown below:

[.text-center]
.container-registry-secret.yaml
[source,yaml,linenums]
----
apiVersion: v1
kind: Secret
metadata:
  annotations:
    build.knative.dev/docker-0: https://index.docker.io/v1/ 
  name: basic-user-pass
stringData:
  password: demopassword
  username: demo
type: kubernetes.io/basic-auth
----

NOTE: The above yaml has dummy values for username, password etc., the actual values will be based on the <<build-set-env,Build Environment Variables>>.

For more details on why we need to do this please check https://github.com/knative/docs/blob/master/docs/build/auth.md#basic-authentication-docker[here].

[#build-edit-build-spec]
== Edit Knative build spec
The Knative build spec is used to create and run the Knative builds. You can find more details on Knative build https://github.com/knative/docs/tree/master/docs/build[here]. In this example we will be using https://buildah.io[Buildah] to perform the build and push of of the container image.

[#build-run-edit-build-spec]
[source,bash,subs="+macros,+attributes",linenums]
----
yq w -i event-greeter-build.yaml 'spec.steps[0].env[0].value' pass:["/workspace/$CONTEXT_DIR"] && \
yq w -i event-greeter-build.yaml 'spec.steps[0].workingDir' pass:["/workspace/$CONTEXT_DIR"] && \
yq w -i event-greeter-build.yaml 'spec.source.git.url' pass:[$SOURCE_REPO_URL] && \
yq w -i event-greeter-build.yaml 'spec.source.git.revision' pass:[$SOURCE_REVISION] && \
yq w -i event-greeter-build.yaml 'spec.steps[0].env[1].value' pass:[$DESTINATION_IMAGE_NAME] 
----
copyToClipboard::build-run-edit-build-spec[]

The above command will generate a knative build specification as shown below:

[.text-center]
.event-greeter-build.yaml
[source,yaml]
----
apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: greeter-build
spec:
  serviceAccountName: build-bot
  source:
    git:
      revision: master
      url: https://github.com/redhat-developer-demos/knative-tutorial-greeter.git
  steps:
    - args:
        - "/usr/local/bin/buildah.sh"
      env:
        - name: WORK_DIR
          value: /workspace/java/quarkus
        - name: DESTINATION_NAME
          value: quay.io/workspace7/build-test:v0.0.1
        # uncomment this if you have MAVEN_MIRROR thats is reachable from your kube cluster
        # speeds up the builds - the example below uses Nexus repo manager installed in host machine
        # - name: MAVEN_MIRROR_URL
        #  value: $http://192.168.64.1:8081/nexus/content/groups/public
      image: quay.io/rhdevelopers/quarkus-java-builder
      name: build-and-push
      # needed for buildah builds to be running as containers
      securityContext:
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
        - mountPath: /root/.m2
          name: m2-cache
        - mountPath: /var/lib/containers
          name: container-storage
      workingDir: /workspace/java/quarkus
  timeout: 60m
  volumes:
    - name: m2-cache
      persistentVolumeClaim:
        claimName: m2-cache
    - name: container-storage
      hostPath:
        path: /var/lib/containers
----

NOTE: The above yaml has dummy values for --context, --destination etc., the actual values will be based on the <<build-set-env,Build Environment Variables>>.

[#build-edit-knative-service]
== Edit Knative service

Run the following command to create the knative service that will use the image created by the `event-greeter-build`.

[#build-run-edit-knative-service]
[source,bash,subs="+macros,+attributes",linenums]
----
yq w -i service.yaml 'spec.runLatest.configuration.revisionTemplate.spec.container.image' pass:[$DESTINATION_IMAGE_NAME] 
----
copyToClipboard::build-run-edit-knative-service[]

[.text-center]
.service-build.yaml
[source,yaml,linenums]
----
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: event-greeter
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          labels:
            app: event-greeter
        spec:
          container:
            image: docker.io/demo/event-greeter:0.0.1
----

NOTE: The above yaml has dummy values for image, the actual values will be based on the <<build-set-env,Build Environment Variables>>.

[#build-apply-prereq-resources]
=== Apply pre-requisite resources

Before we create the build and service, we need to create a few Kubernetes resources that will be used by the build.

Run the following commands to create the pre-requisite resources:

[#build-run-apply-prereq-resources]
[source,bash,subs="+macros,+attributes",linenums]
----
kubectl apply -n {tutorial-namespace} -f container-registry-secret.yaml && \#<1>
kubectl apply -n {tutorial-namespace} -f link:{github-repo}/{build-repo}/knative/build-sa.yaml[build-sa.yaml] && \#<2>
kubectl apply -n {tutorial-namespace} -f link:{github-repo}/{build-repo}/knative/m2-pvc.yaml[m2-pvc.yaml]  && \#<3>
kubectl apply -n {tutorial-namespace} -f link:{github-repo}/{build-repo}/knative/container-storage-pvc.yaml[container-storage-pvc.yaml] #<4>
----
copyToClipboard::build-run-apply-prereq-resources[]

**(OR)**

[#build-run-oc-apply-prereq-resources]
[source,bash,subs="+macros,+attributes",linenums]
----
oc apply -n {tutorial-namespace} -f container-registry-secret.yaml && \#<1>
oc apply -n {tutorial-namespace} -f link:{github-repo}/{build-repo}/knative/build-sa.yaml[build-sa.yaml] && \#<2>
oc apply -n {tutorial-namespace} -f link:{github-repo}/{build-repo}/knative/m2-pvc.yaml[m2-pvc.yaml] && \#<3>
oc apply -n {tutorial-namespace} -f link:{github-repo}/{build-repo}/knative/container-storage-pvc.yaml[container-storage-pvc.yaml] #<4>
----
copyToClipboard::build-run-oc-apply-prereq-resources[]


<1> The Kubernetes secret called `basic-auth-pass`, check https://github.com/knative/docs/blob/master/docs/build/auth.md#basic-authentication-docker[here] for more details
<2> The Kubernetes service account called `build-bot` that will run the build.  Only `build-bot` has access to the secret `basic-auth-pass`. Check https://github.com/knative/docs/blob/master/docs/build/auth.md#basic-authentication-docker[here] for more details
<3> The Kubernetes persistence volume claim used to cache maven artifacts, to make subsequent builds faster
<4> The Kubernetes persistence volume claim  that will be used to mount and store the built contianer images

[#build-create-build]
== Create build 

[#build-run-create-build]
[source,bash,subs="+macros,+attributes"]
----
kubectl apply -n {tutorial-namespace} -f event-greeter-build.yaml
----
copyToClipboard::build-run-create-build[]

**(OR)**

[#build-run-oc-create-build]
[source,bash,subs="+macros,+attributes"]
----
oc apply -n {tutorial-namespace} -f event-greeter-build.yaml
----
copyToClipboard::build-run-oc-create-build[]

[#build-see-what-you-have-deployed]
== See what you have deployed

[#build-show-knative-builds]
=== build 
include::partial$knative-objects.adoc[tag=knative-build]

[NOTE]
====
The builds right now can't be started from the step where it has failed, you always need to start a new build by deleting the existing build followed by creating a new one again.

e.g. 
[source,bash,subs="+macros,+attributes"]
----
kubectl delete -n {tutorial-namespace} -f event-greeter-build.yaml
kubectl apply -n {tutorial-namespace} -f event-greeter-build.yaml
----

**(OR)**

[source,bash,subs="+macros,+attributes"]
----
oc delete -n {tutorial-namespace} -f event-greeter-build.yaml
oc apply -n {tutorial-namespace} -f event-greeter-build.yamll
----
====

[#build-watching-logs]
== Watching logs
include::partial$watching-build-logs.adoc[]

[#build-build-status]
== Checking build status

A successful build will have the container image pushed to the container registry, going by the examples above you should the image `event-greeter:0.0.1 ` in your container registry.

You can check the status of build as shown below:

[source,bash,subs="+macros,+attributes",linenums]
----
kubectl -n {tutorial-namespace} get pods
----

**(OR)**

[source,bash,subs="+macros,+attributes"]
----
oc -n {tutorial-namespace} get pods
----

The above command should return an output as shown below:

[source,bash,subs="+macros,+attributes"]
----
NAME                      READY     STATUS      RESTARTS   AGE
event-greeter-build-pod-cf0174   0/1       Completed   0          10m
----

With this you should also be able to do pull your container images from the registry.

[#build-deploy-service-build]
== Deploy service using Build 

With a successful build you are ready to deploy the service, run the following commands to deploy the service:

[#build-run-deploy-service]
[source,bash,subs="+macros,+attributes"]
----
kubectl apply -n {tutorial-namespace} -f service.yaml
----
copyToClipboard::build-run-deploy-service[]

**(OR)**

[#build-run-oc-deploy-service]
[source,bash,subs="+macros,+attributes"]
----
oc apply -n {tutorial-namespace} -f service.yaml
----
copyToClipboard::build-run-oc-deploy-service[]

After successful deployment of the service we should see a Kubernetes deployment like `event-greeter-8fvqf-deployment` available.

[#build-invoke-service]
== Invoke service 

:k8s-env: minikube
:k8s-cli: kubectl
include::ROOT:partial$invoke-service.adoc[tag=env]

**(OR)**

:k8s-env: minishift
:k8s-cli: oc
include::ROOT:partial$invoke-service.adoc[tag=env]

[#build-run-service-call]
[source,bash,subs="+macros,+attributes",linenums]
----
http POST $IP_ADDRESS \
  'Host:event-greeter.{tutorial-namespace}.example.com'  \
   message="test message"
----
copyToClipboard::build-run-service-call[]

The above command should return an response like:

[source,json]
----
{
    "host": "Event  greeter => 'event-greeter-build-pod-d55571' : 1",
    "message": "test message",
    "time": "04:50:40"
}
----

NOTE: the actual response's host and time properties will be based on your environment

[#build-build-cleanup]
== Cleanup
Before proceeding next chapter let us delete the build and service objects that were created.

[#build-run-cleanup]
[source,bash,subs="+macros,+attributes",linenums]
----
kubectl -n {tutorial-namespace} delete services.serving.knative.dev event-greeter
kubectl -n {tutorial-namespace} delete builds.build.knative.dev event-greeter-build
----
copyToClipboard::build-run-cleanup[]

**(OR)**

[#build-run-oc-cleanup]
[source,bash,subs="+macros,+attributes",linenums]
----
oc -n {tutorial-namespace} delete services.serving.knative.dev event-greeter
oc -n {tutorial-namespace} delete builds.build.knative.dev event-greeter-build
----
copyToClipboard::build-run-oc-cleanup[]

NOTE: You can also delete xref:ROOT:{build-repo}/build.adoc#build-apply-prereq-resources[pre-req resources] that were created if you don't need them anymore.