= Setup
include::_attributes.adoc[]

[[prerequisite]]
== Prerequisite CLI tools

The following CLI tools are required for running the exercises in this tutorial. Please have them installed and configured before you get started with any of the tutorial chapters.

[cols="3*^,3*.",options="header"]
|===
|**Tool**|**macOS**|**Fedora**
ifndef::workshop[]
| `Minikube`
2+| https://kubernetes.io/docs/setup/minikube
| `Minishift`
2+| https://github.com/minishift/minishift/releases
endif::[]
| `oc`
| https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.1.0-rc.4/
| https://mirror.openshift.com/pub/openshift-v4/clients/ocp/4.1.0-rc.4/

| `git`
| https://git-scm.com/download/mac
| `dnf install git`

| `Docker`
| https://docs.docker.com/docker-for-mac/install
| `dnf install docker`

| https://maven.apache.org[Apache Maven]
| `brew install maven`
| `dnf install maven`

| https://github.com/wercker/stern[stern]
| `brew install stern`
| `sudo curl --output /usr/local/bin/stern -L https://github.com/wercker/stern/releases/download/1.6.0/stern_linux_amd64 && sudo chmod +x /usr/local/bin/stern`

| https://github.com/mikefarah/yq[yq]
| `brew install yq`
|  https://github.com/mikefarah/yq/releases/latest

| https://httpie.org/[httpie]
| `brew install httpie`
| `dnf install httpie`

| https://github.com/JoeDog/siege[siege]
| `brew install siege`
| `dnf install siege`

| watch
| `brew install watch`
| `dnf install procps-ng`

| kubectx and kubens
| `brew install kubectx`
| https://github.com/ahmetb/kubectx

|===

[#remote-docker-repository]
== Remote Repository
For some parts of the tutorial, you will be pushing and pulling container images to and from a remote image repository. You will need an account with publish rights. As of this writing, knative works best with https://hub.docker.com[Docker Hub].

[#download-tutorial-sources]
== Download Tutorial Sources
Before we start setting up the environment, let's clone the tutorial sources and set the `TUTORIAL_HOME` environment variable to point to the root directory of the tutorial:

[#cloneRepo]
[source,bash,subs="+macros,+attributes"]
----
git clone -b {workshop-version} https://github.com/redhat-developer-demos/knative-tutorial 
----
copyToClipboard::cloneRepo[]

ifndef::workshop[]
[IMPORTANT,subs="+macros,+attributes"]
====

This tutorial was developed and tested with:

- Knative `{knative-version}`
- Minikube `{minikube-version}`
- OpenShift `{openshift-version}`
- Minishift `{minishift-version}`
====
[#kubernetes-cluster]
== Kubernetes Cluster

include::partial$minikube-setup.adoc[]
include::partial$openshift-setup.adoc[]

endif::[]

ifdef::workshop[]
== Setup Workshop Environment

Please set the following environment variables before running the exercises:

[#setup-workshop-env]
[source,bash,subs="+macros,+attributes"]
----
# This should be your workshop user id like dev001
export WORKSHOP_USER='PUT YOUR USERNAME HERE'
# navigate to the source repo
cd  knative-tutorial
export TUTORIAL_HOME=pass:[`pwd`]

#Windows users
set WORKSHOP_USER='PUT YOUR USERNAME HERE'
set TUTORIAL_HOME=%cd%
----
copyToClipboard::setup-workshop-env[]
endif::[]

ifdef::workshop[]
== OpenShift Project
For this workshop you have been configured with OpenShift project **$WORKSHOP_USER-knativetutorial**, change to your workshop project:

[source,bash,subs="+macros,+attributes"]
----
oc login -u pass:[$WORKSHOP_USER] -password openshift {apiUrl}
oc project $WORKSHOP_USER-knativetutorial
----
endif::[]
