= Setup
include::_attributes.adoc[]

[[prerequisite]]
== Prerequisite CLI tools

The following CLI tools are required for running the exercises in this tutorial. Please have them installed and configured before you get started with any of the tutorial chapters.

[cols="3*^,3*.",options="header"]
|===
|**Tool**|**macOS**|**Fedora**

| `Minikube`
2+| https://kubernetes.io/docs/setup/minikube

| `Minishift`
2+| https://github.com/minishift/minishift/releases

| `git`
| https://git-scm.com/download/mac
| `dnf install git`

| `Docker`
| https://docs.docker.com/docker-for-mac/install
| `dnf install docker`

| https://maven.apache.org[Apache Maven]
| `brew install maven`
| `dnf install maven`

| https://github.com/wercker/stern[stern]
| `brew install stern`
| `sudo curl --output /usr/local/bin/stern -L https://github.com/wercker/stern/releases/download/1.6.0/stern_linux_amd64 && sudo chmod +x /usr/local/bin/stern`

| https://github.com/mikefarah/yq[yq]
| `brew install yq`
|  https://github.com/mikefarah/yq/releases/latest

| https://httpie.org/[httpie]
| `brew install httpie`
| `dnf install httpie`

| https://github.com/JoeDog/siege[siege]
| `brew install siege`
| `dnf install siege`

| watch
| `brew install watch`
| `dnf install procps-ng`

| kubectx and kubens
| `brew install kubectx`
| https://github.com/ahmetb/kubectx

|===

[#download-tutorial-sources]
== Download Tutorial Sources
Before we start setting up the environment, let's clone the tutorial sources and set the `TUTORIAL_HOME` environment variable to point to the root directory of the tutorial:

[#cloneRepo]
[source,bash,subs="+macros,+attributes"]
----
git clone https://github.com/redhat-developer-demos/knative-tutorial 
----
copyToClipboard::cloneRepo[]

The `work` folder in `$TUTORIAL_HOME` can be used to download the demo application resources and refer to them during the exercises. The `work` folder has a README with instructions on the source code repo and git commands to clone the sources.

[IMPORTANT,subs="+macros,+attributes"]
====

This tutorial was developed and tested with:

- Knative `{knative-version}`
- Minikube `{minikube-version}`
- OpenShift `{openshift-version}`
- Minishift `{minishift-version}`
====

[#kubernetes-cluster]
== Kubernetes Cluster

include::partial$minikube-setup.adoc[]
include::partial$openshift-setup.adoc[]

[#setup-work-folder]
== Work folder

The work folder i.e `$TUTORIAL_HOME/work` can be used as a work directory during the build. The README in the work folder has the GitHub repository links of the applications `greeter` and `event-greeter` that will be used in various exercises.
