= Basics and Fundamentals
include::_attributes.adoc[]

At the end of this chapter you will be able to :

* Deploy a Knative service.
* Deploy multiple revisions of a service.
* Choose between different service deployment strategies.
* Run different revisions of a service.

[#basics-prerequisite]
== Prerequisite

include::partial$prereq-cli.adoc[]

[#basics-build-containers]
== Build Containers
include::partial$build-containers.adoc[tag=greeter]

[#basics-deploy-service]
== Deploy Service

Navigate to the tutorial chapter's `knative` folder:

[source,bash,subs="+macros,+attributes"]
----
cd $TUTORIAL_HOME/{basics-repo}/knative
----

The following snippet shows what a Knative service YAML looks like:

.link:{github-repo}/{basics-repo}/knative/service.yaml[service.yaml]
[source,yaml,linenums]
----
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: greeter
spec:
  runLatest: #<1>
    configuration:
      revisionTemplate:
        spec:
          container:
            image: dev.local/rhdevelopers/greeter:0.0.1 #<2>
----

<1> Makes Knative always run the latest revision of the deployment
<2> It is very important that the image is a fully qualified docker image name with tag. For more details on this, see xref:ROOT:faq.adoc#faq-q2[Question 2 of FAQ]

The service can be deployed using the following command:
 
:doc-sec: basics-rev1-deploy
:url: {github-repo}/{basics-repo}/knative/service.yaml
:url-alt-text: service.yaml
include::ROOT:partial$deploy-knative-resources.adoc[]

After successful deployment of the service we should see a Kubernetes Deployment named similar to `greeter-nsrbr-deployment` available:

[tabs]
====
kubectl::
+
--
[#basics-run-get-deployments]
[source,bash,subs="+macros,+attributes"]
----
kubectl get deployments -n {tutorial-namespace}
----
copyToClipboard::basics-run-get-deployments[]
--
oc::
+
--
[#basics-run-oc-get-deployments]
[source,bash,linenums,subs="+macros,+attributes"]
----
oc get deployments -n {tutorial-namespace}
----
copyToClipboard::basics-run-oc-get-deployments[]
--
====

[NOTE]
====
* The actual deployment name may vary in your setup
====

[#basics-invoke-service]
== Invoke Service
[tabs]
====
Minikube::
+
--
:k8s-env: minikube
:k8s-cli: kubectl
:doc-sec: bis
include::ROOT:partial$invoke-service.adoc[tag=*]
--
Minishift::
+
--
:k8s-env: minishift
:k8s-cli: oc
:doc-sec: bis
include::ROOT:partial$invoke-service.adoc[tag=*]
--
====

The `http` command should return a response containing a line similar to **Hi  greeter => '6fee83923a9f' : 1**

NOTE: Sometimes the response might not be returned immediately especially when the pod is coming up from dormant state. In that case, repeat service invocation.

[#basics-see-what-you-have-deployed]
== See what you have deployed

The service-based deployment strategy that we did now will create many Knative resources, the following commands will help you to query and find what has been deployed.

[#basics-show-knative-services]
=== service 

include::partial$knative-objects.adoc[tag=knative-services]

[#basics-show-knative-configs]
=== configuration

include::partial$knative-objects.adoc[tag=knative-configs]

[#basics-show-knative-routes]
=== routes

include::partial$knative-objects.adoc[tag=knative-routes]

When the service was invoked with `http $IP_ADDRESS 'Host:greeter.knativetutorial.example.com'`, you noticed that we added a **Host** header to the request with value `greeter.knativetutorial.example.com`. This FQDN is automatically assigned to your Knative service by the Knative Routes and uses the following format: `**<service-name>.<namespace>.<domain-suffix>**`.

[NOTE]
====
* The domain suffix in this case __example.com__ is configurable via the config map **config-domain** of **knative-serving** namespace.
====

[#rev1-basics-show-knative-revisions]
=== revisions
:doc-sec: rev1
include::partial$knative-objects.adoc[tag=knative-revisions]

[TIP]
====
* add `-oyaml` to the commands above to see more details
====

[#deploying-new-revision]
== Deploy a New Revision of a Service

As Knative follows https://12factor.net[12-Factor] application principles, any https://12factor.net/config[configuration] change will trigger creation of a new revision of the deployment.
 
To deploy a new revision of the greeter service, we will add an environment variable to the existing service as shown below:

[#basics-service-rev2]
=== Service revision 2

.link:{github-repo}/{basics-repo}/knative/service-env.yaml[service-env.yaml]
[source,yaml,linenums]
----
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: greeter
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: dev.local/rhdevelopers/greeter:0.0.1
            env:
             - name: MESSAGE_PREFIX #<1>
               value: Namaste
----

<1> Adding an environment variable that will be used as the message prefix

Let us deploy the new revision using the command:

:doc-sec: basics-rev2-deploy
:url: {github-repo}/{basics-repo}/knative/service-env.yaml
:url-alt-text: service-env.yaml
include::ROOT:partial$deploy-knative-resources.adoc[]


After successful deployment of the service we should see a Kubernetes deployment called `greeter-cqgcf-deployment`.

Now if you list revisions, you will see two of them, named similar to `greeter-cqgcf` and `greeter-nsrbr`.

[#rev2-basics-show-knative-revisions]
=== revisions
:doc-sec: rev2
include::partial$knative-objects.adoc[tag=knative-revisions]

<<basics-invoke-service,Invoking Service>> will now show an output like **Namaste  greeter => '6fee83923a9f' : 1**, where __Namaste__ is the value we configured via environment variable in the Knative service resource file.

[#basics-pinning-revision]
== Pinning Service to a Revision

As you noticed, Knative service always routes traffic to the **latest** revision of the service deployment, due to the **runLatest** attribute in the <<basics-service-rev2,service resource file>>.

Let us now make the greeter service use the first revision created, the one using the default `MESSAGE_PREFIX`.

[TIP]
====
You can use the <<rev1-basics-show-knative-revisions, show Knative service revisions>> command to find the available revisions for the greeter service.
====

=== Service pinned to first revision

.link:{github-repo}/{basics-repo}/knative/service-pinned-rev1.yaml[service-pinned.yaml]
[source,yaml,linenums]
----
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: greeter
spec:
  release: #<1>
    revisions:
    - greeter-nsrbr
  configuration:
    revisionTemplate:
      spec:
        container:
          image: dev.local/rhdevelopers/greeter:0.0.1
          env:
            - name: MESSAGE_PREFIX
              value: Namaste
          livenessProbe:
            httpGet:
              path: /healthz
          readinessProbe:
            httpGet:
              path: /healthz
----

<1> The **release** attribute in the service resource file will make Knative use the revision specified in the **revisions** attribute.

[IMPORTANT]
====
The names of revisions may be different in your setup
====

Let us redeploy the greeter service by pinning it to the first revision that was created:
[tabs]
====
kubectl::
+
--
[#run-pinned-revision]
[source,bash,subs="+macros,+attributes"]
----
PIN_REVISION=`kubectl get rev -n {tutorial-namespace} -l serving.knative.dev/service=greeter -l serving.knative.dev/configurationGeneration=1 | awk 'NR==2{print $1}'` && \
cat service-pinned.yaml | yq w - "spec.release.revisions[+]" $PIN_REVISION | kubectl -n {tutorial-namespace} apply -f -
----
copyToClipboard::run-pinned-revision[]
--
oc::
+
--
[#run-oc-pinned-revision]
[source,bash,subs="+macros,+attributes"]
----
PIN_REVISION=`oc get rev -n {tutorial-namespace} -l serving.knative.dev/service=greeter -l serving.knative.dev/configurationGeneration=1 | awk 'NR==2{print $1}'` && \
cat service-pinned.yaml | yq w - "spec.release.revisions[+]" $PIN_REVISION | oc -n {tutorial-namespace}  apply -f -
----
copyToClipboard::run-oc-pinned-revision[]
--
====

<<basics-invoke-service,Invoking Service>> will produce output similar to **Hi  greeter => '6fee83923a9f' : 1**

[#basics-cleanup]
== Cleanup

[tabs]
====
kubectl::
+
--
[#basics-run-cleanup]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n {tutorial-namespace} delete services.serving.knative.dev greeter
----
copyToClipboard::basics-run-cleanup[]
--
oc::
+
--
[#basics-run-oc-cleanup]
[source,bash,subs="+macros,+attributes"]
----
oc -n {tutorial-namespace} delete services.serving.knative.dev greeter
----
copyToClipboard::basics-run-oc-cleanup[]
--
====
