= Basics and Fundamentals
include::_attributes.adoc[]

At the end of this chapter you will be able to :

* Deploy a Knative service.
* Deploy multiple revisions of a service.
* Choose between different service deployment strategies.
* Running different revisions of a service.

[#basics-prerequisite]
== Prerequisite

include::partial$prereq-cli.adoc[]

[#basics-build-containers]
== Build Containers
include::partial$build-containers.adoc[tag=greeter]

[#basics-deploy-service]
== Deploy Service

Navigate to the tutorial chapter's `knative` folder:

[source,bash,subs="+macros,+attributes"]
----
cd $TUTORIAL_HOME/{basics-repo}/knative
----

The following snippet shows how a Knative service YAML will look like:


.link:{github-repo}/{basics-repo}/knative/service.yaml[service.yaml]
[source,yaml,linenums]
----
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: greeter
spec:
  runLatest: #<1>
    configuration:
      revisionTemplate:
        spec:
          container:
            image: dev.local/rhdevelopers/greeter:0.0.1 #<2>
----

<1> Makes Knative to always run the latest revision of the deployment
<2> It is very important that the image is a fully qualified name docker image name with tag. For more details on this xref:ROOT:faq.adoc#faq-q2[Question 2 of FAQ]

The service could be deployed using the command:

[#basics-run-svc-apply]
[source,bash,subs="+macros,+attributes"]
----
kubectl apply -n {tutorial-namespace} -f link:{github-repo}/{basics-repo}/knative/service.yaml[service.yaml]
----
copyToClipboard::basics-run-svc-apply[]

**(OR)**

[#basics-run-oc-svc-apply]
[source,bash,linenums,subs="+macros,+attributes"]
----
oc apply -n {tutorial-namespace} -f link:{github-repo}/{basics-repo}/knative/service.yaml[service.yaml]
----
copyToClipboard::basics-run-oc-svc-apply[]

After successful deployment of the service we should see a kubernetes deployment like `greeter-nsrbr-deployment` available.

[NOTE]
====
* The actual deployment name may vary in your setup
====

[#basics-invoke-service]
== Invoke Service
:k8s-env: minikube
:k8s-cli: kubectl

include::ROOT:partial$invoke-service.adoc[tag=*]

**(OR)**

:k8s-env: minishift
:k8s-cli: oc
include::ROOT:partial$invoke-service.adoc[tag=*]

The last curl command should return a response like **Hi  greeter => '6fee83923a9f' : 1**

NOTE: Sometimes the response might not be returned immediately especially when the pod is coming up from dormant state, at those times try giving request again

[#basics-see-what-you-have-deployed]
== See what you have deployed

The service-based deployment strategy that we did now will create many Knative resources, the following commands will help you to query and find what has been deployed.

[#basics-show-knative-services]
=== service 

include::partial$knative-objects.adoc[tag=knative-services]

[#basics-show-knative-configs]
=== configuration

include::partial$knative-objects.adoc[tag=knative-configs]

[#basics-show-knative-routes]
=== routes

include::partial$knative-objects.adoc[tag=knative-routes]

When the service was invoked with `curl -H "Host:greeter.knativetutorial.example.com" $IP_ADDRESS`,you noticed that we added a **Host** header to the request with value `greeter.knativetutorial.example.com`,this FQDN is automatically assigned to your Knative service by the Knative Routes,it uses the format like `**<service-name>.<namespace>.<domain-suffix>**`.

[NOTE]
====
* The domain suffix in this case __example.com__ is configurable via the config map **config-domain** of **knative-serving** namespace.
====

[#basics-show-knative-revisions]
=== revisions
include::partial$knative-objects.adoc[tag=knative-revisions]

[TIP]
====
* add `-oyaml` to the commands above to see more details
====

[#deploying-new-revision]
== Deploy new Revision Service

As Knative follows https://12factor.net[12-Factor] application principles, any new https://12factor.net/config[configuration] change will trigger new revision of the deployment. 
 
To deploy a new revision of the greeter service, we will add an environment variable to the existing service as shown below:

[#basics-service-rev2]
=== Service revision 2

.link:{github-repo}/{basics-repo}/knative/service-env.yaml[service-env.yaml]
[source,yaml,linenums]
----
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: greeter
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: dev.local/rhdevelopers/greeter:0.0.1
            env:
             - name: MESSAGE_PREFIX #<1>
               value: Namaste
----

<1> Adding an environment variable that will be used as the message prefix

Let us deploy the new revision using the command:

[#basics-run-service-env]
[source,bash,subs="+macros,+attributes"]
----
kubectl apply -n {tutorial-namespace} -f link:{github-repo}/{basics-repo}/knative/service-env.yaml[service-env.yaml]
----
copyToClipboard::basics-run-service-env[]

**(OR)**
[#oc-basics-run-service-env]
[source,bash,subs="+macros,+attributes"]
----
oc apply -n {tutorial-namespace} -f link:{github-repo}/{basics-repo}/knative/service-env.yaml[service-env.yaml]
----
copyToClipboard::oc-basics-run-service-env[]

After successful deployment of the service we should see a kubernetes deployment called `greeter-cqgcf-deployment`.

Now running the <<basics-show-knative-revisions,command>> will show two revisions namely `greeter-cqgcf` and `greeter-nsrbr`.

<<basics-invoke-service,Invoking Service>> will now show an output like **Namaste  greeter => '6fee83923a9f' : 1**, where __Namaste__ is the value that we configured via environment variable in the Knative service resource file.

[#basics-pinning-revision]
== Pinning service to a revision

As you noticed that the Knative services always routes the traffic to the **latest** revision of the service deployment, thats because of the **runLatest** attribute in <<basics-service-rev2,service resource file>>.

Let us now make the greeter service use first revision created i.e. the one using the default `MESSAGE_PREFIX`. 

[TIP]
====
You can use the get <<basics-show-knative-revisions, show knative revisions>> command to find the available revisions for the greeter service.
====

=== Service pinned to first revision

.link:{github-repo}/{basics-repo}/knative/service-pinned-rev1.yaml[service-pinned.yaml]
[source,yaml,linenums]
----
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: greeter
spec:
  release: #<1>
    revisions:
    - greeter-nsrbr
  configuration:
    revisionTemplate:
      spec:
        container:
          image: dev.local/rhdevelopers/greeter:0.0.1
          env:
            - name: MESSAGE_PREFIX
              value: Namaste
          livenessProbe:
            httpGet:
              path: /healthz
          readinessProbe:
            httpGet:
              path: /healthz
----

<1> The **release** attribute in service resource file will make Knative use the revision specified in the **revisions** attribute.

[IMPORTANT]
====
The value of revisions might be different in your setup 
====

Let redeploy the greeter service by pinning it to the first revision that was created:

[#run-pinned-revision]
[source,bash,subs="+macros,+attributes"]
----
FIRST_REVISION=`kubectl get rev -l serving.knative.dev/service=greeter -l serving.knative.dev/configurationGeneration=1 | awk 'NR==2{print $1}'` && \
cat service-pinned.yaml | yq w - "spec.release.revisions[+]" $FIRST_REVISION | kubectl -n {tutorial-namespace} apply -f -
----
copyToClipboard::run-pinned-revision[]

**(OR)**

[#run-oc-pinned-revision]
[source,bash,subs="+macros,+attributes"]
----
FIRST_REVISION=`kubectl get rev -l serving.knative.dev/service=greeter -l serving.knative.dev/configurationGeneration=1 | awk 'NR==2{print $1}'` && \
cat service-pinned.yaml | yq w - "spec.release.revisions[+]" $FIRST_REVISION | oc -n {tutorial-namespace}  apply -f -
----
copyToClipboard::run-oc-pinned-revision[]

<<basics-invoke-service,Invoking Service>> will now show an output like **Hi  greeter => '6fee83923a9f' : 1**

[#basics-cleanup]
== Cleanup

[#basics-run-cleanup]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n {tutorial-namespace} delete services.serving.knative.dev greeter
----
copyToClipboard::basics-run-cleanup[]

**(OR)**

[#basics-run-oc-cleanup]
[source,bash,subs="+macros,+attributes"]
----
oc -n {tutorial-namespace} delete services.serving.knative.dev greeter
----
copyToClipboard::basics-run-oc-cleanup[]

