= Configurations and Routes
include::_attributes.adoc[]

At the end of this chapter you will be able to understand and know how to :

* Deploy Knative configurations and routes separately.
* Distribute traffic between revisions of a service.

[#crtd-prerequisite]
== Prerequisite 
include::partial$prereq-cli.adoc[]

[#ctrd-build-containers]
== Build Containers

include::partial$build-containers.adoc[tag=greeter]

[#crtd-deploy-configuration]
== Deploy Configuration

In the previous chapter we saw how we can deploy services using a holistic service resource file, in this chapter we will see how to deploy the service using configurations and route files.

Navigate to the tutorial chapter's folder:

[#navigate-crtd-folder]
[source,bash,subs="+macros,+attributes"]
----
cd $TUTORIAL_HOME/{configs-and-routes-repo}
----
copyToClipboard::navigate-crtd-folder[]

=== Deploy Configuration revision 1

The following snippet shows how a Knative configuration resource YAML looks like:
[.text-center]
.link:{github-repo}/{configs-and-routes-repo}/config/configuration-rev1.yaml[configuration-rev1.yaml]
[source,yaml,linenums]
----
apiVersion: serving.knative.dev/v1alpha1
kind: Configuration
metadata:
  name: greeter
spec:
  revisionTemplate:
    metadata:
      labels:
        app: greeter
    spec:
      container:
        image: dev.local/rhdevelopers/greeter:0.0.1 #<1>
----

<1> It is very important that the image is a fully qualified docker image name, including a  tag. For more details on this xref:ROOT:faq.adoc#faq-q2[Question 2 of FAQ].

The service is then deployed using:

:doc-sec: crtd-rev1-apply
:url: {github-repo}/{configs-and-routes-repo}/config/configuration-rev1.yaml
:url-alt-text: config/configuration-rev1.yaml
include::ROOT:partial$deploy-knative-resources.adoc[]

After the deployment was successful, we should see a kubernetes deployment like `greeter-wlcn4-deployment`.

[#crtd-invoke-service]
== Invoke Service

[tabs]
====
Minikube::
+
--
:k8s-env: minikube
:k8s-cli: kubectl
:doc-sec: ctrd-is
include::ROOT:partial$invoke-service.adoc[tag=*]
--
Minishift::
+
--
:k8s-env: minishift
:k8s-cli: oc
:doc-sec: ctrd-is
include::ROOT:partial$invoke-service.adoc[tag=*]
--
====

The command will return `HTTP 404` as there are no routes deployed yet. Let us now deploy a route.

[#crtd-deploy-route]
== Deploy Route
Let us now deploy a route that will route all the traffic to the configuration we just deployed.
[.text-center]
.link:{github-repo}/{configs-and-routes-repo}/route/route_default.yaml[route_default.yaml]
[source,yaml,linenums]
----
apiVersion: serving.knative.dev/v1alpha1
kind: Route
metadata:
  name: greeter
spec:
  traffic:
    - configurationName: greeter
      percent: 100
----

:doc-sec: crtd-route-default-apply
:url: {github-repo}/{configs-and-routes-repo}/route/route_default.yaml
:url-alt-text: route/route_default.yaml
include::ROOT:partial$deploy-knative-resources.adoc[]

<<crtd-invoke-service,Invoking Service>> now should return a response like **Hi  greeter => '9be9ccd9a2e3' : 1**

NOTE: Sometimes the response might not be returned immediately especially when the pod is coming up from a dormant state. You might need to be a little patient :) .

[#crtd-see-what-you-have-deployed]
== See what you have deployed

As we did not deploy a service this time

[#crtd-show-knative-services]
=== service 
include::partial$knative-objects.adoc[tag=knative-services]

will throw an error as there are no knative services is deployed as part of the __configuration + routes__ based deployment strategy. 

[#crtd-show-knative-configs]
=== configuration
include::partial$knative-objects.adoc[tag=knative-configs]

[#crtd-show-knative-routes]
=== routes
include::partial$knative-objects.adoc[tag=knative-routes]

When the service is invoked with `http $IP_ADDRESS "Host:greeter.knativetutorial.example.com"`, you noticed that we added a **Host** header to the `http` command with the value `greeter.knativetutorial.example.com`. This FQDN is automatically assigned to your Knative service by the Knative route we created. It follows a format `<route-name>.<namespace>.<domain-suffix>`.

[NOTE]
====
* The `domain-suffix` (in this case __example.com__) is configurable via the config map **config-domain** in the **knative-serving** namespace.
====

[#crtd-show-knative-revisions]
=== revisions
include::partial$knative-objects.adoc[tag=knative-config-revisions]

[TIP]
====
* add `-oyaml` to the commands above to see more details
====

[#crtd-deploying-new-revision]
== Deploy a new revision

Knative follows a revision model for its configurations. Each time you change something in the `revisionTemplate` Knative will effectively generate a new revision and thus a new deployment. In this example we add a new environment variable to demonstrate that mechanism. 

=== Deploy configuration revision 2 
[.text-center]
.link:{github-repo}/{configs-and-routes-repo}/config/configuration-rev2.yaml[configuration-rev2.yaml]
[source,yaml,linenums]
----
apiVersion: serving.knative.dev/v1alpha1
kind: Configuration
metadata:
  name: greeter
spec:
  revisionTemplate:
    metadata:
      labels:
        app: greeter
    spec:
      container:
        image: dev.local/rhdevelopers/greeter:0.0.1
        env: #<1>
          - name: MESSAGE_PREFIX
            value: Namaste
----

<1> Adding an environment variable that will be used a message prefix.

Let us deploy the new revision using the command:

:doc-sec: crtd-rev2-apply
:url: {github-repo}/{configs-and-routes-repo}/config/configuration-rev2.yaml
:url-alt-text: config/configuration-rev2.yaml
include::ROOT:partial$deploy-knative-resources.adoc[]

After the deployment was successful we should see a kubernetes deployment like `greeter-tb57l-deployment`.

Now running the <<crtd-show-knative-revisions,show revisions command>> will list all the revisions sorted in descending order of its creation.

<<crtd-invoke-service,Invoking Service>> will now show an output like **Namaste  greeter => '9be9ccd9a2e3' : 1**, where __Namaste__ is the value that we configured for `MESSAGE_PREFIX` via environment variable in the Knative service resource file.

[#crtd-distributing-traffic]
== Distributing traffic

When deploying services with service object based approach, the service resource will take care of traffic distribution either 100% to latest or pinned revision. In this section we will explore how we can deploy routes to distribute traffic between deployed revisions.

Before we start to apply routes, let us open a new terminal and run the following command `$TUTORIAL_HOME/{configs-and-routes-repo}/bin/call.sh`, this command will keep sending requests to greeter route every two seconds which allows us to monitor the changes to the responses as we keep applying the route that will distribute the traffic between the available two revisions.

[#ctrd-traffic-distribution-polling]
=== Polling the service

We need to run the service invocation in loop to see the results of traffic distribution.

[#crtd-poll-sh]
[source,bash,subs="macros+,attributes+"]
----
#!/bin/bash
set -eu
while true
do
  http --body $IP_ADDRESS 'Host:greeter.{tutorial-namespace}.example.com'
  sleep 3
done;
----
copyToClipboard::crtd-poll-sh[]

TIP: Copy and save the above contents to a script file e.g. `$TUTORIAL_HOME/work/poll.sh`

[#crtd-define-revisions]
=== Define revisions

For easier explanation and understanding lets give logical names to the revisions and set them to environment variables:

[tabs]
====
kubectl::
+
--
[#ctrd-def-revisions]
[source,bash,subs="+macros,+attributes",linenums]
----
REVISION_1=`kubectl -n knativetutorial get rev -l serving.knative.dev/configuration=greeter --sort-by="{.metadata.creationTimestamp}" | awk 'NR==2{print $1}'`
REVISION_2=`kubectl -n knativetutorial get rev -l serving.knative.dev/configuration=greeter --sort-by="{.metadata.creationTimestamp}" | awk 'NR==3{print $1}'`
----
copyToClipboard::ctrd-def-revisions[]
--
oc::
+
--
[#ctrd-def-oc-revisions]
[source,bash,subs="+macros,+attributes",linenums]
----
REVISION_1=`oc -n knativetutorial get rev -l serving.knative.dev/configuration=greeter --sort-by="{.metadata.creationTimestamp}" | awk 'NR==2{print $1}'`
REVISION_2=`oc -n knativetutorial get rev -l serving.knative.dev/configuration=greeter --sort-by="{.metadata.creationTimestamp}" | awk 'NR==3{print $1}'`
----
copyToClipboard::ctrd-def-oc-revisions[]
--
====

[#crtd-all-rev1]
=== Send all traffic to revision 1
:doc-sec: all-rev1
:url: {github-repo}/{configs-and-routes-repo}/route/route_all_rev1.yaml
:url-text: route/route_all_rev1
:revision: $REVISION_1
include::ROOT:partial$crtd-send-traffic.adoc[]

If <<crtd-poll-sh,poll the service>> for some time,  you will notice the service always goes to your revision 1 e.g output will be something like **Hi  greeter => '9be9ccd9a2e3' : 1**.

[#crtd-all-rev2]
=== Send all traffic to revision 2

:doc-sec: all-rev2
:url: {github-repo}/{configs-and-routes-repo}/route/route_all_to_revision.yaml
:url-text: route/route_all_to_revision.yaml
:revision: $REVISION_2
include::ROOT:partial$crtd-send-traffic.adoc[]

If <<crtd-poll-sh,poll the service>> for some time,  you will notice the service always goes to your revision 2 e.g output will be something like **Namaste  greeter => '9be9ccd9a2e3' : 1**.

[#crtd-all-rev1-rev2-50]
=== 50-50 split between revision 1 and revision 2

:doc-sec: rev1-50-rev2-50
:url: {github-repo}/{configs-and-routes-repo}/route/route_rev1-50_rev2-50.yaml
:url-text: route/route_rev1-50_rev2-50.yaml
:revision: $REVISION_1
include::ROOT:partial$crtd-send-traffic.adoc[]

If <<crtd-poll-sh,poll the service>> for some time,  you will notice the service is distributed between revision 1 and revision 2 e.g output will be mix of responses like **Hi  greeter => '9be9ccd9a2e3' : 1** and **Namaste  greeter => '9be9ccd9a2e3' : 1**. You will also notice the traffic is distributed approximately 50% between the two revisions.

[#crtd-all-rev1-rev2-75-25]
=== 75-25 split between revision 1 and revision 2

:doc-sec: rev1-75-rev2-25
:url: {github-repo}/{configs-and-routes-repo}/route/route_rev1-75_rev2-25.yaml
:url-text: route/route_rev1-75_rev2-25.yaml
:revision: $REVISION_1
include::ROOT:partial$crtd-send-traffic.adoc[]

If <<crtd-poll-sh,poll the service>> for some time,  you will notice the service is distributed between revision 1 and revision 2 e.g output will be mix of responses like **Hi  greeter => '9be9ccd9a2e3' : 1** and **Namaste  greeter => '9be9ccd9a2e3' : 1**. You will also notice the traffic is distributed approximately 75-25% between the two revisions.

[#crtd-all-rev1-rev2-10-90]
=== 10-90 split between revision 1 and revision 2

:doc-sec: rev1-rev2-10-90
:url: {github-repo}/{configs-and-routes-repo}/route/route_rev1-10_rev2-90.yaml
:url-text: route/route_rev1-10_rev2-90.yaml
:revision: $REVISION_1
include::ROOT:partial$crtd-send-traffic.adoc[]

If <<crtd-poll-sh,poll the service>> for some time,  you will notice the service is distributed between revision 1 and revision 2 e.g output will be mix of responses like **Hi  greeter => '9be9ccd9a2e3' : 1** and **Namaste  greeter => '9be9ccd9a2e3' : 1**. You will also notice the traffic is distributed approximately 10-90% between the two revisions.

[#ctrd-cleanup]
== Cleanup
[tabs]
====
kubectl::
+
--
[#crtd-run-cleanup]
[source,bash,subs="+macros,+attributes",linenums]
----
kubectl -n {tutorial-namespace} delete configurations.serving.knative.dev greeter
kubectl -n {tutorial-namespace} delete routes.serving.knative.dev greeter
----
copyToClipboard::crtd-run-cleanup[]
--
oc::
+
--
[#crtd-run-oc-cleanup]
[source,bash,subs="+macros,+attributes",linenums]
----
oc -n {tutorial-namespace} delete configurations.serving.knative.dev greeter
oc -n {tutorial-namespace} delete routes.serving.knative.dev greeter
----
copyToClipboard::crtd-run-oc-cleanup[]
--
====
