= FAQs

[#faq-q1]
== How to access the Knative services ?

When looking up the IP address to use for accessing your app, you need to look up the NodePort for the **istio-ingressgateway** well as the IP address used for minishift. You can use the following command to look up the value to use for the pass:[{IP_ADDRESS}] placeholder used in the sample
[source,bash,linenums]
----
#!/bin/bash
# In Knative 0.2.x and prior versions, the `knative-ingressgateway` service was used instead of `istio-ingressgateway`.
INGRESSGATEWAY=knative-ingressgateway

# The use of `knative-ingressgateway` is deprecated in Knative v0.3.x.
# Use `istio-ingressgateway` instead, since `knative-ingressgateway`
# will be removed in Knative v0.4.
if kubectl get configmap config-istio -n knative-serving &> /dev/null; then
    INGRESSGATEWAY=istio-ingressgateway
fi

IP_ADDRESS="$(minishift ip):$(kubectl get svc $INGRESSGATEWAY --namespace istio-system --output 'jsonpath={.spec.ports[?(@.port==80)].nodePort}')"

# calling a knative service named greeter
curl -H "Host:greeter.knativetutorial.example.com" $IP_ADDRESS
----

[#faq-q2]
== Why `dev.local` suffixes for container images?

.Tag Digest
***
> Docker images with v2 or later format have a content-addressable identifier called a `digest`. The digest is a hash of the image content, so images with the same digest are guaranteed to have idetical content.
[.text-right]
__**Source**: https://docs.docker.com/engine/reference/commandline/images/#list-image-digests__

***

Given a deployment like the following (note that resource definitions have been trimmed for brevity):

[source,yaml,linenums]
----
apiVersion: apps/v1
kind: Deployment
metadata:
   name: helloworld
spec:
  template:
    spec:
       containers:
         - name: my-container
           image: gcr.io/knative-samples/helloworld-go

. . .
----

When you deploy this application in kubernetes, the deployment will look like:

[source,yaml,linenums]
----
apiVersion: apps/v1
kind: Deployment
metadata:
   name: helloworld
spec:
  template:
    spec:
       containers:
          - name: my-container
            image: gcr.io/knative-samples/helloworld-go@sha256:98af362ceca8191277206b3b3854220ce125924b28a1166126296982e33882d0
. . .
----

The container image name `gcr.io/knative-samples/helloworld-go` was resolved to its digest `gcr.io/knative-samples/helloworld-go@sha256:98af362ceca8191277206b3b3854220ce125924b28a1166126296982e33882d0`. Kubernetes extracts the digest from the image manifest.  This process of resolving  image tag to its digest is informally called as “Tag to Digest”.

Knative Serving deployments, by default, resolve the container images to digest during the deployment process. Knative Serving has been configured to skip the resolution of image name/tag to image digest for registries ko.local and dev.local, which can be used for local development builds where the underlying image contents are subject to change during the  development process.

[TIP]
====
You can also add any of the other image repo suffixes from skipping to digest by editing the configmap **config-controller** of **knative-serving** namespace and appending your repo to `registriesSkippingTagResolving` attribute of the configmap.

The following command shows an example how to add a registry **my.docker.registry** to the be skipped:

```
val=$(oc -n knative-serving get cm config-controller -oyaml | yq r - data.registriesSkippingTagResolving | awk '{print $1",my.docker.registry"}')

oc -n knative-serving get cm config-controller -oyaml | yq w - data.registriesSkippingTagResolving $val | oc apply -f -
```
====

[#faq-q3]
== What is a "revision" in simpler terms?
A https://github.com/knative/serving/blob/master/docs/spec/overview.md#revision[Revision] is an immutable snapshot of code and configuration. Each change to an application's https://github.com/knative/serving/blob/master/docs/spec/overview.md#configuration[Configuration] creates a new *Revision*, which allows an application to be rolled back to any previous “known good configuration”.
