= Knative Tutorial

Serverless epitomizes the very benefits of what cloud platforms promise: offload the management of infrastructure while taking advantage of a consumption model for the actual utilization of services. While there are a number of serverless frameworks out there, Knative is the first specifically designed for Kubernetes and OpenShift.

> Serverless computing refers to the concept of building and running applications that do not require server management. It describes a finer-grained deployment model where applications, bundled as one or more functions, are uploaded to a platform and then executed, scaled, and billed in response to the exact demand needed at the moment”

[.text-right]
__**Source**__:  https://www.cncf.io/blog/2018/02/14/cncf-takes-first-step-towards-serverless-computing/ 

This tutorial will act as a step-by-step guide in helping you understand Knative, starting with setup, fundamental concepts such as service, configuration, revision etc., and finally deploying some use cases which could help deploying serverless applications at enterprises.

This content is brought to you by http://developers.redhat.com[Red Hat Developer Program] - Register today!
