= Setup
include::_attributes.adoc[]

[#prerequisite]
== Prerequisite CLI tools

The following CLI tools are required for running the exercises in this tutorial. Please have them installed and configured before you get started with any of the tutorial chapters.

[cols="4*^,4*."]
|===
|**Tool** |**macOS** |**Fedora** | **Remarks**
| `minikube` 
| https://kubernetes.io/docs/setup/minikube
| https://kubernetes.io/docs/setup/minikube
|

| `minishift` 
| https://github.com/minishift/minishift/releases
| https://github.com/minishift/minishift/releases
|

| https://maven.apacge.org[Apache Maven]
| `brew install maven`
| `dnf install maven`
|

| https://github.com/wercker/stern[stern]
| `brew install stern`
| `sudo curl --output /usr/local/bin/stern -L https://github.com/wercker/stern/releases/download/1.6.0/stern_linux_amd64 && sudo chmod +x /usr/local/bin/stern`
|

| http://xmlstar.sourceforge.net/[xmlstarlet]
| `brew install xmlstarlet`
| http://xmlstar.sourceforge.net/
|

| https://github.com/mikefarah/yq[yq]
| `brew install yq`
|  https://github.com/mikefarah/yq/releases/latest
|

| https://httpie.org/[httpie]
| `brew install httpie`
| `dnf install httpie`
|

| https://golang.org[go]
| `brew install golang`
| https://dl.google.com/go/go1.11.5.linux-amd64.tar.gz
|

| https://github.com/rakyll/hey[hey]
| `go get -u github.com/rakyll/hey`
| `go get -u github.com/rakyll/hey`
| Add `hey` to the path using the command `export PATH=$HOME/go/bin:$PATH`

| https://jsonnet.org/
|`brew install jsonnet`
| https://github.com/google/jsonnet
|

| watch
|`brew install watch`
| it will be pre-installed
|
|===

[#download-tutorial-sources]
== Download Tutorial Sources
Before we start to setting up the environment, lets clone the tutorial sources and call the cloned folder as `$TUTORIAL_HOME`

[source,bash]
----
git clone https://github.com/redhat-developer-demos/knative-tutorial
----

The `work` folder in `$TUTORIAL_HOME` can be used to download the demo application resources and refer them during the exercises. The `work` folder has a README, which has instructions on source code repo and git commands to clone the sources.

[IMPORTANT]
====

This tutorial was developed and tested with:

- OpenShift `v3.11`
- Knative `v0.3.0`
- minikube `v0.33.1`
- minishift `v1.30.0+186b034`
====

[#install-knative]
== Install Knative 

[#install-knative-minikube]
=== Minikube
https://github.com/knative/docs/blob/master/install/Knative-with-Minikube.md[Knative with Minikube]

[#install-knative-openshift]
=== OpenShift 

For OpenShift Knative installations we will use the OpenShift Cloud Function's https://github.com/openshift-cloud-functions/knative-operators[Knative Operators].

Clone the Knative Operator sources locally:

[source,bash,linenums]
-----
cd $TUTORIAL_HOME/work
git clone https://github.com/openshift-cloud-functions/knative-operators
cd knative-operators
-----


[#install-knative-ocp]
==== OCP

If you have an existing OpenShift cluster then run the following commands:

[source,bash,linenums]
-----
./etc/scripts/install.sh
-----

If you need more details about the installation or customizations refer https://github.com/openshift-cloud-functions/Documentation/blob/master/knative-OCP.md[Knative with OpenShift].

[#install-knative-minishift]
==== minishift

Run the following commands to configure Knative with minishift:

[source,bash,linenums]
-----
./etc/scripts/install-on-minishift.sh #<1>
-----

<1> It will create a minishift profile and install knative.  It also assumes that you already have minishift and your computer has 10GB or more of memory

[#configure-openshift-project]
== Configuring OpenShift project for Knative applications

[source,bash,linenums]
----
oc new-project knativetutorial
oc adm policy add-scc-to-user privileged -z default #<1>
oc adm policy add-scc-to-user anyuid -z default
----

<1> The `oc adm policy` adds the **privileged** https://docs.okd.io/3.10/admin_guide/manage_scc.html[Security Context Constraints(SCCs)]to the **default** Service Account. The SCCs are the precursor to the PSP (Pod Security Policy) mechanism in kubernetes.


[.text-center]
**(OR)**

[source,bash]
----
kubectl create namespace knativetutorial
----

[#setup-work-folder]
== Work folder

The work folder i.e `$TUTORIAL_HOME/work` can be used as a work directory during the build. The README in the work folder as the GitHub repository links of the applications `greeter` and `event-greeter` that will be used in various exercises.
