= Setup
include::_attributes.adoc[]

[#prerequisite]
== Prerequisite CLI tools

The following CLI tools are required for running the exercises in this tutorial. Please have them installed and configured before you get started with any of the tutorial chapters.

[cols="4*^,4*."]
|===
|**Tool** |**macOS** |**Fedora** | **Remarks**
| `minikube` 
| https://kubernetes.io/docs/setup/minikube
| https://kubernetes.io/docs/setup/minikube
|

| `minishift` 
| https://github.com/minishift/minishift/releases
| https://github.com/minishift/minishift/releases
|

| https://maven.apacge.org[Apache Maven]
| `brew install maven`
| `dnf install maven`
|

| https://github.com/wercker/stern[stern]
| `brew install stern`
| `sudo curl --output /usr/local/bin/stern -L https://github.com/wercker/stern/releases/download/1.6.0/stern_linux_amd64 && sudo chmod +x /usr/local/bin/stern`
|

| http://xmlstar.sourceforge.net/[xmlstarlet]
| `brew install xmlstarlet`
| http://xmlstar.sourceforge.net/
|

| https://github.com/mikefarah/yq[yq]
| `brew install yq`
|  https://github.com/mikefarah/yq/releases/latest
|

| https://httpie.org/[httpie]
| `brew install httpie`
| `dnf install httpie`
|

| https://golang.org[go]
| `brew install golang`
| https://dl.google.com/go/go1.11.5.linux-amd64.tar.gz
|

| https://github.com/rakyll/hey[hey]
| `go get -u github.com/rakyll/hey`
| `go get -u github.com/rakyll/hey`
| Add `hey` to the path using the command `export PATH=$HOME/go/bin:$PATH`

| https://jsonnet.org/
|`brew install jsonnet`
| https://github.com/google/jsonnet
|

| watch
|`brew install watch`
| it will be pre-installed
|

| kubectx and kubens
| `brew install kubectx`
| https://github.com/ahmetb/kubectx
|
|===

[#download-tutorial-sources]
== Download Tutorial Sources
Before we start to setting up the environment, lets clone the tutorial sources and call the cloned folder as `$TUTORIAL_HOME`

[source,bash]
----
git clone https://github.com/redhat-developer-demos/knative-tutorial
----

The `work` folder in `$TUTORIAL_HOME` can be used to download the demo application resources and refer them during the exercises. The `work` folder has a README, which has instructions on source code repo and git commands to clone the sources.

[IMPORTANT]
====

This tutorial was developed and tested with:

- Knative `v0.3.0`
- minikube `v0.34.1`
- OpenShift `v3.11`
- minishift `v1.30.0+186b034`
====

[#kubernetes-cluster]
== Kubernetes Cluster

[#install-knative-minikube]
=== Minikube

[#start-minikube]
==== Configure and Start minikube 

Before installing Knative and its components, we need to add few startup config to minikube.

[source,bash,subs="+macros,+attributes"]
----
minikube start -p knative --memory=8192 --cpus=4 \#<1> 
  --vm-driver=hyperkit \#<2>
  --disk-size=50g \
  --extra-config=apiserver.enable-admission-plugins="LimitRanger,NamespaceExists,NamespaceLifecycle,ResourceQuota,ServiceAccount,DefaultStorageClass,MutatingAdmissionWebhook"
----

<1> Starting a profile named **knative**
<2> If you are on linux then use `--vm-driver=kvm2`

[#install-knative-istio]
==== Install Istio 

[source,bash,subs="+macros,+attributes"]
----
kubectl apply --filename {knative-serving-repo}/{knative-version}/istio-crds.yaml
kubectl apply --filename {knative-serving-repo}/{knative-version}/istio.yaml
----

[NOTE]
====
Installation of istio components will take some time and its highly recommended that you start Knative components installation only after you see all istio component pods are running. The istio pods can be watched using the command:
[source,bash,subs="+macros,+attributes"]
----
kubectl -n istio-system get pods -w 
----
You can use kbd:[CTRL + c ] to terminate the watch
====

A successful istio install will have the pods running in `istio-system` namespace as shown below:

[source,bash]
----
NAME                                       READY   STATUS      RESTARTS   AGE
cluster-local-gateway-547467ccf6-857mx     1/1     Running     0          6h35m
istio-citadel-7d64db8bcf-xgdh7             1/1     Running     0          6h35m
istio-cleanup-secrets-7mjbl                0/1     Completed   0          6h35m
istio-egressgateway-6ddf4c8bd6-sglg6       1/1     Running     0          6h35m
istio-galley-7dd996474-4jhr4               1/1     Running     0          6h35m
istio-ingressgateway-84b89d647f-f9n4h      1/1     Running     0          6h35m
istio-pilot-86bb4fcbbd-ptz7n               2/2     Running     0          6h35m
istio-pilot-86bb4fcbbd-s9qxl               2/2     Running     0          6h34m
istio-pilot-86bb4fcbbd-xd887               2/2     Running     0          6h34m
istio-policy-5c4d9ff96b-tzkbw              2/2     Running     0          6h35m
istio-sidecar-injector-6977b5cf5b-9wsjw    1/1     Running     0          6h35m
istio-statsd-prom-bridge-b44b96d7b-x85xr   1/1     Running     0          6h35m
istio-telemetry-7676df547f-55p6c           2/2     Running     0          6h35m
knative-ingressgateway-75644679c7-5xwx6    1/1     Running     0          6h27m
----

[#install-knative-serving]
===== **Install Knative Serving**

[source,bash,subs="+macros,+attributes"]
----
kubectl apply --filename {knative-serving-repo}/{knative-version}/serving.yaml
----

[NOTE]
====
Installation of knative serving components will take some time, the status of the knative serving pods can be watched using the command:
[source,bash,subs="+macros,+attributes"]
----
kubectl -n knative-serving get pods -w 
----
You can use kbd:[CTRL + c ] to terminate the watch
====

A successful Knative serving install will have the pods running in `knative-serving` as shown below:

[source,bash]
----
NAME                          READY   STATUS    RESTARTS   AGE
activator-69b8474d6b-fhnwq    2/2     Running   0          6h33m
autoscaler-6579b57774-lcjd2   2/2     Running   0          6h33m
controller-66cd7d99df-6lt2t   1/1     Running   0          6h33m
webhook-6d9568d-htxlt         1/1     Running   0          6h33m
----

[#install-knative-build]
===== **Install Knative Build** 

[source,bash,subs="+macros,+attributes"]
----
kubectl apply --filename {knative-build-repo}/{knative-version}/release.yaml
----

[NOTE]
====
Installation of knative build components will take some time, the status of the  knative serving pods can be watched using the command:
[source,bash,subs="+macros,+attributes"]
----
kubectl -n knative-build get pods -w 
----
You can use kbd:[CTRL + c ] to terminate the watch
====

A successful Knative build install will have the pods running in `knative-build` as shown below:

[source,bash]
----
NAME                                READY   STATUS    RESTARTS   AGE
build-controller-658d64d9bd-4m7l9   1/1     Running   0          6h32m
build-webhook-6bb747665f-trjxg      1/1     Running   0          6h32m
----

[#install-knative-eventing]
===== **Install Knative Eventing** 

[source,bash,subs="+macros,+attributes"]
----
kubectl apply --filename {knative-eventing-repo}/{knative-version}/release.yaml
kubectl apply --filename {knative-sources-repo}/{knative-version}/release.yaml
----

[NOTE]
====
Installation of knative eventing components will take some time, the status of the  knative serving pods can be watched using the command:
[source,bash,subs="+macros,+attributes"]
----
kubectl -n knative-sources get pods -w 
kubectl -n knative-eventing get pods -w 
----
You can use kbd:[CTRL + c ] to terminate the watch
====

A successful Knative eventing install will have the pods running `knative-eventing` and `knative-sources` in as shown below:

.knative-eventing namespace

[source,bash]
----
NAME                                            READY   STATUS    RESTARTS   AGE
eventing-controller-cfbb757bd-lg5zk             1/1     Running   0          6h35m
in-memory-channel-controller-75d6cc4b77-f8bfl   1/1     Running   0          6h35m
in-memory-channel-dispatcher-c89db8bb8-ktr26    2/2     Running   1          6h35m
webhook-5fbb8dbcc7-gk6cx                        1/1     Running   0          6h35m
----

.knative-sources namespace

[source,bash]
----
NAME                   READY   STATUS    RESTARTS   AGE
controller-manager-0   1/1     Running   0          6h35m
----

[#set-knative-tutorial-ns]
==== Configuring Kubernetes namespace

We will use a non default kubernetes namespace called `knativetutorial` for all the tutorial exercises.

[source,bash]
----
kubectl create namespace knativetutorial
----

[#install-knative-openshift]
=== OpenShift 

For OpenShift Knative installations we will use the OpenShift Cloud Function's https://github.com/openshift-cloud-functions/knative-operators[Knative Operators].

Clone the Knative Operator sources locally:

[source,bash,linenums]
-----
cd $TUTORIAL_HOME/work
git clone https://github.com/openshift-cloud-functions/knative-operators
cd knative-operators
-----

[#install-knative-ocp]
==== OCP

If you have an existing OpenShift cluster then run the following commands:

[source,bash,linenums]
-----
./etc/scripts/install.sh
-----

If you need more details about the installation or customizations refer https://github.com/openshift-cloud-functions/Documentation/blob/master/knative-OCP.md[Knative with OpenShift].

[#install-knative-minishift]
==== minishift

Run the following commands to configure Knative with minishift:

[source,bash,linenums]
-----
./etc/scripts/install-on-minishift.sh #<1>
-----

<1> It will create a minishift profile and install knative.  It also assumes that you already have minishift and your computer has 10GB or more of memory

[#configure-openshift-project]
==== Configuring OpenShift project for Knative applications

[source,bash,linenums]
----
oc new-project knativetutorial
oc adm policy add-scc-to-user privileged -z default #<1>
oc adm policy add-scc-to-user anyuid -z default
----

<1> The `oc adm policy` adds the **privileged** https://docs.okd.io/3.10/admin_guide/manage_scc.html[Security Context Constraints(SCCs)]to the **default** Service Account. The SCCs are the precursor to the PSP (Pod Security Policy) mechanism in kubernetes.

[#setup-work-folder]
== Work folder

The work folder i.e `$TUTORIAL_HOME/work` can be used as a work directory during the build. The README in the work folder as the GitHub repository links of the applications `greeter` and `event-greeter` that will be used in various exercises.
