[#camelk-setup]
== Setup
include::_attributes.adoc[]

[#camelk-prerequisite]
== Prerequisite

ifndef::workshop[]
include::knative-tutorial:ROOT:partial$prereq-cli.adoc[]
endif::[]

[#install-camel-k]
== Install Camel-k

Download the latest camel-k release from https://github.com/apache/camel-k/releases/latest[here]. Extract the content and add the binary `kamel` to the PATH.

[IMPORTANT]
====
As of building this tutorial the latest **kamel** version was `{kamel-version}`
==== 

ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#camel-k-k8s-install]
[source,bash,subs="+quotes,+attributes,+macros"]
-----
kamel install --wait
-----
copyToClipboard::camel-k-k8s-install[]

As with other installations in this tutorial, this process will take a few minutes for the Camel-K pods to be up and running.  You can monitor the progress of the installation by watching the pods in namespace `{tutorial-namespace}`.

.Camel K Pods
[#camel-k-watch-pods]
[source,bash,subs="+quotes,+attributes,+macros"]
-----
watch kubectl -n {tutorial-namespace} get pods
-----
copyToClipboard::camel-k-watch-pods[]

[NOTE]
=====
The Camel-k install will take some time, please wait for the successful installation before proceeding to the further sections of this tutorial.
=====

A successful camel-K setup will have the following pods running/completed in `{tutorial-namespace}` namespace:

[source,bash,subs="+macros,+attributes"]
-----
NAME                                READY   STATUS      RESTARTS   AGE
camel-k-operator-84d7896b68-9mfdv   1/1     Running     0          2m7s
-----
--
oc::
+
--

Camel-K is installed using its https://operatorhub.io/operator/camel-k[operator].Use the Operator Hub in OpenShift webconsole to install the Camel-K operator.

Once the operator is deployed successfully, run the following command to setup `Camel-K` in the namespace:

[source,bash,subs="+quotes,+attributes,+macros"]
----
kamel install --cluster-setup --skip-operator-setup
----

[NOTE]
======
In OpenShift, the `kamel install` command will not install Camel-K operator in each namespace, rather its done one time at cluster level when installing the Operator.
======

endif::[]
ifndef::workshop[]
--
endif::[]
====

[#configure-maven-repo]
== Configure Camel-k to build faster 

Camel-K uses https://maven.apache.org[Apache Maven] to build the integration kits and its related containers. The Apache Maven settings for Camel K are stored in a ConfigMap `camel-k-maven-settings` in the {tutorial-namespace} namespace. One of the ways to make the build faster is by using a maven repository manager such as https://www.sonatype.com/nexus-repository-oss[Sonatype Nexus], the repository manager helps in caching the maven artifacts from remote repositories and serves them from local the subsequent times they are asked to be downloaded.

Edit the ConfigMap using the command:

ifndef::workshop[]
[tabs]
====
kubectl::
+
--
[#camel-k-maven-config]
[source,bash,subs="+quotes,+attributes,+macros"]
----
kubectl edit -n {tutorial-namespace} cm camel-k-maven-settings
----
copyToClipboard::camel-k-maven-config[]
--
oc::
+
--
[#oc-camel-k-maven-config]
[source,bash,subs="+quotes,+attributes,+macros"]
----
oc edit  -n {tutorial-namespace} cm camel-k-maven-settings
----
copyToClipboard::oc-camel-k-maven-config[]
endif::[]
ifndef::workshop[]
--
endif::[]
====

The command above by default opens the ConfigMap YAML in vi. We can use the environment variable `KUBE_EDITOR`, to allow us to edit the YAML with the editor of our choice. For example setting `export KUBE_EDITOR=code -w`, will make the `kubectl edit` commands to open the Kubernetes resource YAML in https://code.visualstudio.com/[vscode].

The following listing shows the Camel-K maven settings configured to use a Sonatype Nexus repository as its mirror:

.Using Sonatype Nexus mirror
[source,yaml,subs="attributes+"]
----
apiVersion: v1
data:
  settings.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
https://maven.apache.org/xsd/settings-1.0.0.xsd">
      <localRepository></localRepository>
      <mirrors>
        <mirror>
          <id>central</id>
          <name>central</name>
          <url>http://nexus:8081/nexus/content/groups/public</url> # <1>
          <mirrorOf>*</mirrorOf>
        </mirror>
      </mirrors>
      ...
    </settings>
kind: ConfigMap
metadata:
  labels:
    app: camel-k
  name: camel-k-maven-settings
  namespace: {tutorial-namespace}
----
<1> This repository address needs to be updated as per your cluster setting. In example above the installed the Sonatype Nexus in the {tutorial-namespace}.

[NOTE]
====
If you don't have a Sonatype nexus repository, you can deploy one into the cluster using the deployment `$TUTORIAL_HOME/install/utils/nexus/app.yaml`.
====
