= Basics and Fundamentals
include::_attributes.adoc[]

:service-file: service.yaml
:greeter-image: quay.io/rhdevelopers/knative-tutorial-greeter:quarkus

At the end of this chapter you will be able to :

* Deploy a Knative service
* View the Kubernetes resources created by Knative
* Invoke the deployed Knative Service

ifndef::workshop[]
[#basics-prerequisite]
== Prerequisite

include::serving:partial$prereq-cli.adoc[]

endif::[]

[#basics-deploy-service]
== Deploy Service

Navigate to the tutorial chapter's folder {basics-repo}:

[#basics-nav-folder]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cd $TUTORIAL_HOME/{basics-repo}
----

The following snippet shows what a Knative service YAML looks like:

.link:{github-repo}/{basics-repo}/{service-file}[{service-file}]
[source,yaml,subs="+macros,attributes+"]
----
include::serving:example${basics-repo}/{service-file}[]
----

The service can be deployed using the following command:

include::serving:partial$deploy-knative-resources.adoc[tags=tab-1;basic;tab-2]

After successful deployment of the service we should see a Kubernetes Deployment named similar to `greeter-nsrbr-deployment` available:

[#basics-run-get-deployments]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl get deployments
----

NOTE: The actual deployment name may vary in your setup

// TODO: show this with OpenShift logo
[IMPORTANT,caption=OpenShift]
[%hardbreaks]
====
If you are on *OpenShift*, then you can deploy a Knative service by just click of buttons via *OpenShift* web console.

&nbsp;

video::h9F6ynUQHaU[youtube,width=640,height=480]
====

[#basics-invoke-service]
== Invoke Service
ifndef::workshop[]
[tabs]
====
Minikube::
+
--
include::serving:partial$invoke-service.adoc[tags=**;!workshop-call;!workshop-call-params]
--
OpenShift::
+
--
include::serving:partial$invoke-service.adoc[tag=workshop-call]
--
====
endif::[]

ifdef::workshop[]
include::serving:partial$invoke-service.adoc[tag=workshop-call]
endif::[]

The `http` command should return a response containing a line similar to:

[source,bash]
[.console-output]
----
Hi  greeter => '6fee83923a9f' : 1
----

NOTE: Sometimes the response might not be returned immediately especially when the pod is coming up from dormant state. In that case, repeat service invocation.

[#basics-see-what-you-have-deployed]
== Knative Resources

The Knative service that we deployed now, creates many Knative resources, the following commands will help you to query and find those resources:

[#basics-show-knative-services]
=== service 

include::serving:partial$knative-objects.adoc[tag=knative-services]

[#basics-show-knative-configs]
=== configuration

include::serving:partial$knative-objects.adoc[tag=knative-configs]

[.console-output]
[source,bash]
----
NAME      LATESTCREATED      LATESTREADY       READY
greeter   greeter-sxnzq-1    greeter-sxnzq-1    True
----

[#basics-show-knative-routes]
=== routes

include::serving:partial$knative-objects.adoc[tag=knative-routes]

[#rev1-basics-show-knative-revisions]
=== revisions
:doc-sec: rev1
include::serving:partial$knative-objects.adoc[tag=knative-revisions]

[.console-output]
[source,bash]
----
NAME            CONFIG NAME   K8S SERVICE NAME   GENERATION   READY 
greeter-sxnzq-1    greeter       greeter-sxnzq-1       1            True
----

[TIP]
====
* add `-oyaml` to the commands above to see more details
====

[#basics-cleanup]
== Cleanup
[tabs]
====
kn::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kn service delete greeter
----
--
{kubernetes-cli}::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl delete services.serving.knative.dev greeter
----
--
====

