= Basics and Fundamentals
include::_attributes.adoc[]

:service-file: service.yaml
:greeter-image: quay.io/rhdevelopers/knative-tutorial-greeter:quarkus

At the end of this chapter you will be able to :

* Deploy a Knative service.
* Deploy multiple revisions of a service.
* Run different revisions of a service via traffic definition.

ifndef::workshop[]
[#basics-prerequisite]
== Prerequisite

include::serving:partial$prereq-cli.adoc[]

endif::[]

[#basics-deploy-service]
== Deploy Service

Navigate to the tutorial chapter's folder {basics-repo}:

[#basics-nav-folder]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cd $TUTORIAL_HOME/{basics-repo}
----

The following snippet shows what a Knative service YAML looks like:

.link:{github-repo}/{basics-repo}/{service-file}[{service-file}]
[source,yaml,subs="+macros,attributes+"]
----
include::serving:example${basics-repo}/{service-file}[]
----

The service can be deployed using the following command:

include::serving:partial$deploy-knative-resources.adoc[tags=tab-1;basic;tab-2]

[tabs]
====
kn::
+
--
[.console-output]
[source,bash,subs="attributes+"]
----
Creating service 'greeter' in namespace 'knativetutorial':

  0.015s The Configuration is still working to reflect the latest desired specification.
  0.076s The Route is still working to reflect the latest desired specification.
  0.105s Configuration "greeter" is waiting for a Revision to become ready.
  8.550s ...
  8.607s Ingress has not yet been reconciled.
  8.660s unsuccessfully observed a new generation
  8.845s Ready to serve.

Service 'greeter' created to latest revision 'greeter-sxnzq-1 ' is available at URL:
http://greeter.{tutorial-namespace}.{minikube-nip-io}
----
--
{kubernetes-cli}::
+
--
After successful deployment of the service we should see a Kubernetes Deployment named similar to `greeter-nsrbr-deployment` available:

[#basics-run-get-deployments]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl get deployments -n {tutorial-namespace}
----

[NOTE]
=====
* The actual deployment name may vary in your setup
=====
--
====

[#basics-invoke-service]
== Invoke Service
ifndef::workshop[]
[tabs]
====
Minikube::
+
--
include::serving:partial$invoke-service.adoc[tags=**;!workshop-call;!workshop-call-params]
--
OpenShift::
+
--
include::serving:partial$invoke-service.adoc[tag=workshop-call]
--
====
endif::[]

ifdef::workshop[]
include::serving:partial$invoke-service.adoc[tag=workshop-call]
endif::[]

The `http` command should return a response containing a line similar to:

[source,bash]
[.console-output]
----
Hi  greeter => '6fee83923a9f' : 1
----

NOTE: Sometimes the response might not be returned immediately especially when the pod is coming up from dormant state. In that case, repeat service invocation.

[#basics-see-what-you-have-deployed]
== See what you have deployed

The service-based deployment strategy that we did now will create many Knative resources, the following commands will help you to query and find what has been deployed.

[#basics-show-knative-services]
=== service 

include::serving:partial$knative-objects.adoc[tag=knative-services]

[#basics-show-knative-configs]
=== configuration

include::serving:partial$knative-objects.adoc[tag=knative-configs]

[.console-output]
[source,bash]
----
NAME      LATESTCREATED      LATESTREADY       READY
greeter   greeter-sxnzq-1    greeter-sxnzq-1    True
----

[#basics-show-knative-routes]
=== routes

include::serving:partial$knative-objects.adoc[tag=knative-routes]

[IMPORTANT]
====
For all the examples in the tutorial we have configured the xref:setup:minikube.adoc#configure-ingress-to-gateway[Ingress Controller and domain], which will use the domain suffix format like `**<service-name>.<namespace>.<minikube ip>.nip.io**`.

If you have not using the Ingress controller configuration then the service has to be invoked like `http $IP_ADDRESS 'Host:greeter.knativetutorial.example.com'`, you noticed that we added a **Host** header to the request with value `greeter.knativetutorial.example.com`. This FQDN is automatically assigned to your Knative service by the Knative Routes and uses the following format: `**<service-name>.<namespace>.<domain-suffix>**`.

====

[#rev1-basics-show-knative-revisions]
=== revisions
:doc-sec: rev1
include::serving:partial$knative-objects.adoc[tag=knative-revisions]

[.console-output]
[source,bash]
----
NAME            CONFIG NAME   K8S SERVICE NAME   GENERATION   READY 
greeter-sxnzq-1    greeter       greeter-sxnzq-1       1            True
----

[TIP]
====
* add `-oyaml` to the commands above to see more details
====

[#deploying-new-revision]
== Deploy a New Revision of a Service

.Twelve-factor app
****
https://12factor.net/[12factor.net] defines the twelve-factor app as a methodology for building software-as-a-service apps that:

- Use declarative formats for setup automation, to minimize time and cost for new developers joining the project;
- Have a clean contract with the underlying operating system, offering maximum portability between execution environments;
- Are suitable for deployment on modern cloud platforms, obviating the need for servers and systems administration;
- Minimize divergence between development and production, enabling continuous deployment for maximum agility;
- And can scale up without significant changes to tooling, architecture, or development practices.
- The twelve-factor methodology can be applied to apps written in any programming language, and which use any combination of backing services (database, queue, memory cache, etc).
****
 
To deploy a new revision of the greeter service, we will add an environment variable to the existing service as shown below:

[#basics-service-rev2]
=== Service revision 2

:service-file: service-env.yaml

.link:{github-repo}/{basics-repo}/{service-file}[{service-file}]
[source,yaml,subs="+macros,attributes+"]
----
include::serving:example${basics-repo}/{service-file}[]
----

Adding an environment variable that will be used as the message prefix

Let us deploy the new revision using the command:

include::serving:partial$deploy-knative-resources.adoc[tags=tab-1;env;tab-2]

[tabs]
====
kn::
+
--
[.console-output]
[source,subs="+macros,+attributes"]
----
Updating Service 'greeter' in namespace 'knativetutorial':

  0.026s The Configuration is still working to reflect the latest desired specification.
 13.509s Traffic is not yet migrated to the latest revision.
 13.554s Ingress has not yet been reconciled.
 13.618s unsuccessfully observed a new generation
 13.781s Ready to serve.

Service 'greeter' updated to latest revision 'greeter-njxyx-2' is available at URL:
http://greeter.{tutorial-namespace}.{minikube-nip-io}
----
--
{kubernetes-cli}::
+
--
After successful deployment of the service we should see a Kubernetes deployment called `greeter-v2-deployment`.

Now if you list revisions, you will see two of them, named similar to `greeter-v1` and `greeter-v2`.
--
====

[#rev2-basics-show-knative-revisions]
=== revisions
:doc-sec: rev2
include::serving:partial$knative-objects.adoc[tag=knative-revisions]

[.console-output]
[source,bash]
----
NAME              SERVICE   TRAFFIC   TAGS   GENERATION   AGE     CONDITIONS   READY   REASON
greeter-njxyx-2   greeter   100%             2            3m50s   3 OK / 4     True
greeter-sxnzq-1   greeter                    1            37m     3 OK / 4     True
----

<<basics-invoke-service,Invoking Service>> will now show an output like:
[source,bash,subs="+macros,+attributes"]
[.console-output]
----
Namaste  greeter => '6fee83923a9f' : 1**
----
Where __Namaste__ is the value we configured via environment variable in the Knative service resource file.

[#basics-cleanup]
== Cleanup
[tabs]
====
kn::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kn service -n {tutorial-namespace} delete greeter
----
--
{kubernetes-cli}::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n {tutorial-namespace} delete services.serving.knative.dev greeter
----
--
====

