[[channels-and-subs]]
= Channel and Subscribers
include::_attributes.adoc[]
//Define vars
:greeter-image: quay.io/rhdevelopers/knative-tutorial-greeter:quarkus

Channels::
  Channels are an event forwarding and persistence layer where each channel is a separate Kubernetes Custom Resource.  A Channel may be backed by Apache Kafka or InMemoryChannel.  This recipe focuses on InMemoryChannel.

Subscriptions::
  Subscriptions are how you register your service to listen to a particular channel.

:service-file: channel.yaml
[#eventing-channel]
== Channel(Sink)

The https://en.wikipedia.org/wiki/Event-driven_architecture#Event_channel[channel or sink] is an interface between the <<eventing-source,event source>> and the <<eventing-subscriber,subscriber>>. The channels are built in to store the incoming events and distribute the event data to the subscribers. When forwarding event to subscribers the channel transforms the event data as per http://cloudevents.io[CloudEvent] specification.

[#eventing-create-event-channel]
=== Create Event Channel
.link:{github-repo}/{eventing-repo}/channel.yaml[channel.yaml]
[source,yaml,subs="attributes+,+macros"]
----
apiVersion: messaging.knative.dev/v1beta1
kind: Channel
metadata:
  name: eventinghello-ch #<1> 
----

<1> The name of the channel. Knative makes it addressable, i.e. resolveable to a target (a consumer service)

Run the following commands to create the channel:

include::eventing:partial$deploy-knative-resources.adoc[tags=tab-1;channel;tab-2]

[#eventing-verify-event-channel]
==== Verification

[tabs]
====
kn::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kn channel list -n {tutorial-namespace}
----
--
{kubernetes-cli}::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n {tutorial-namespace} get \
  channels.messaging.knative.dev 
----
--
====

Running  the above command should return the following result:

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
NAME             READY URL
eventinghello-ch True  http://eventinghello-ch-kn-channel.{tutorial-namespace}.svc.cluster.local
----

[#eventing-source]
== Event Source

The event source listens to external events e.g. a kafka topic or for a file on a FTP server. It is responsible to drain the received event(s) along with its data to a configured https://en.wikipedia.org/wiki/Sink_(computing)[sink].

:service-file: event-source.yaml
[#eventing-create-event-source]
=== Create Event Source
.link:{github-repo}/{eventing-repo}/event-source.yaml[event-source.yaml]
[source,yaml,subs="attributes+,+macros"]
----
apiVersion: sources.knative.dev/v1alpha2
kind: PingSource
metadata:
  name: event-greeter-ping-source
spec:
  schedule: "*/2 * * * *"
  jsonData: '{"message": "Thanks for doing Knative Tutorial"}'
  sink:
   ref:
    apiVersion: messaging.knative.dev/v1alpha1 # <1>
    kind: Channel # <2>
    name: eventinghello-ch
----

<1> The Channel API is in api-group `messaging.eventing.knative.dev`
<2> Kind is `Channel` instead of direct to a specific service; default is InMemoryChannel implementation

Run the following commands to create the event source resources:

include::eventing:partial$deploy-knative-resources.adoc[tags=tab-1;ev-ping-channel;tab-2]

[#eventing-verify-event-source]
==== Verification

[tabs]
====
kn::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kn source ping -n {tutorial-namespace} list
----

Running  the above command should return the following result:

[.console-output]
[source,bash]
----
NAME                        SCHEDULE      SINK                       AGE   CONDITIONS   READY   REASON
event-greeter-ping-source   */2 * * * *   Channel:eventinghello-ch   24s   4 OK / 4     True
----

--
kubectl::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n {tutorial-namespace} get pingsource.sources.knative.dev 
----

Running  the above command should return the following result:

[.console-output]
[source,bash]
----
NAME                        READY   REASON   SINK                                                                 AGE
event-greeter-ping-source   True             http://eventinghello-ch-kn-channel.kn-cheatsheet.svc.cluster.local   5s
----

--
====



[#eventing-subscriber]
== Event Subscriber

The event subscription is responsible of connecting the channel(sink) with the service. Once a service is connected to a channel it starts receiving the events (cloud events).

:service-file: eventing-helloa-sink.yaml
[#eventing-create-subscribers-services]
=== Create Subscriber Services
.link:{github-repo}/{eventing-repo}/eventing-helloa-sink.yaml[eventing-helloa-sink.yaml]
[source,yaml,subs="attributes+,+macros"]
----
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: eventinghelloa
spec:
  template:
    metadata:
      name: eventinghelloa-v1 #<1>
      annotations:
        autoscaling.knative.dev/target: "1"
    spec:
      containers:
      - image: quay.io/rhdevelopers/eventinghello:0.0.2
----
<1> The string of `eventinghelloa` will help you identify this particular service.

.link:{github-repo}/{eventing-repo}/eventing-hellob-sink.yaml[eventing-hellob-sink.yaml]
[source,yaml,subs="attributes+,+macros"]
----
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: eventinghellob
spec:
  template:
    metadata:
      name: eventinghellob-v1 <1>
      annotations:
        autoscaling.knative.dev/target: "1"
    spec:
      containers:
      - image: quay.io/rhdevelopers/eventinghello:0.0.2
----

<1> The string of `eventinghellob` will help you identify this particular service.

:service-file: eventing-helloa-sink.yaml
:sink-service-name: eventinghelloa
:revision-name: eventinghelloa-v1
==== Deploy eventing-helloa-sink
include::eventing:partial$deploy-knative-resources.adoc[tags=tab-1;eventing-hello-sink;tab-2]

:service-file: eventing-hellob-sink.yaml
:sink-service-name: eventinghellob
:revision-name: eventinghellob-v1
==== Deploy eventing-hellob-sink

include::eventing:partial$deploy-knative-resources.adoc[tags=tab-1;eventing-hello-sink;tab-2]

[#eventing-create-subscriber]
=== Create Channel Subscribers

Now create the appropriate `Subscription` for `eventinghelloa` to the Channel `eventinghello-ch`:

[source,yaml]
----
apiVersion: messaging.knative.dev/v1beta1
kind: Subscription
metadata:
  name: eventinghelloa-sub
spec:
  channel:
    apiVersion: messaging.knative.dev/v1beta1
    kind: Channel
    name: eventinghello-ch
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: eventinghelloa
----

And create the appropriate `Subscription` for `eventinghellob` to the Channel `eventinghello-ch`:

[source,yaml]
----
apiVersion: messaging.knative.dev/v1beta1
kind: Subscription
metadata:
  name: eventinghellob-sub
spec:
  channel:
    apiVersion: messaging.knative.dev/v1beta1
    kind: Channel
    name: eventinghello-ch
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: eventinghellob
----

:service-file: eventing-helloa-sub.yaml
==== Subscribe to eventinghelloa 
include::eventing:partial$deploy-knative-resources.adoc[tags=tab-1;sub-helloa-sink;tab-2]

:service-file: eventing-hellob-sub.yaml
==== Subscribe to eventinghelloab
include::eventing:partial$deploy-knative-resources.adoc[tags=tab-1;sub-hellob-sink;tab-2]

[#eventing-verify-subscriber]
==== Verification

[tabs]
====
kn::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kn subscription -n {tutorial-namespace} list
----

Running  the above command should return the following result:

[.console-output]
[source,bash]
----
NAME                 CHANNEL                    SUBSCRIBER            REPLY   DEAD LETTER SINK   READY   REASON
eventinghelloa-sub   Channel:eventinghello-ch   ksvc:eventinghelloa                              True
eventinghellob-sub   Channel:eventinghello-ch   ksvc:eventinghellob                              True
----
--
{kubernetes-cli}::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n {tutorial-namespace} \
   get subscription.messaging.knative.dev 
----

Running  the above command should return the following result:

[.console-output]
[source,bash]
----
NAME                       AGE
eventinghelloa-sub         39s
eventinghellob-sub         39s
----

--
====


If you wait approximately 2 minutes for the PingSource then you will see both `eventinghelloa` and `eventinghellob` begin to run in the {tutorial-namespace}.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
watch 'kubectl get pods -n {tutorial-namespace}'
----

.Watch pods in the {tutorial-namespace}
[.console-output]
[source,bash]
----
NAME                                                      READY STATUS  AGE
eventinghelloa-v1-deployment-d86bf4847-hvbk6               2/2   Running 5s
eventinghellob-v1-deployment-5c986c7586-4clpb              2/2   Running 5s
----

[#eventing-see-what-you-have-deployed]
== See what you have deployed

=== channel
include::eventing:partial$knative-objects.adoc[tag=knative-event-channel]

=== source
include::eventing:partial$knative-objects.adoc[tag=knative-event-ping-sources]

=== subscriptions
include::eventing:partial$knative-objects.adoc[tag=knative-event-subscribers]

TIP: Add `-oyaml` to the above commands to get more details about each object that were queried for. 

[#eventing-cleanup]
== Cleanup

[tabs]
====
kn::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kn service delete -n {tutorial-namespace} eventinghelloa
kn subscription delete eventinghelloa-sub --namespace {tutorial-namespace}
kn service delete -n {tutorial-namespace}  eventinghellob
kn subscription delete eventinghellob-sub --namespace {tutorial-namespace}
kn source ping delete -n {tutorial-namespace} event-greeter-ping-source
kn channel delete -n {tutorial-namespace} eventinghello-ch
----
--
{kubernetes-cli}::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n {tutorial-namespace} delete -f eventing-helloa-sink.yaml
kubectl -n {tutorial-namespace} delete -f eventing-helloa-sub.yaml
kubectl -n {tutorial-namespace} delete -f eventing-hellob-sink.yaml
kubectl -n {tutorial-namespace} delete -f eventing-hellob-sub.yaml
kubectl -n {tutorial-namespace} delete -f event-source.yaml
kubectl -n knativetutorial delete -f channel.yaml
----
--
====


