[[source-to-sink]]
= Eventing Source to Sink
include::_attributes.adoc[]
//Define vars
:greeter-image: quay.io/rhdevelopers/knative-tutorial-greeter:quarkus

include::eventing:partial$eventing-snippets.adoc[tag=eventing-nav-folder]

:service-file: eventinghello-source.yaml
[#eventing-source]
== Event Source

*Knative Eventing Sources* are software components that emit events.  The job of a Source is to connect to, drain, capture and potentially buffer events; often from an external system and then relay those events to the *Sink*.

Knative Eventing Sources installs the following four sources out-of-the-box:

[#eventing-get-api-resources]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl api-resources --api-group='sources.knative.dev'
----

[.console-output]
[source,bash]
----
NAME              APIGROUP                      NAMESPACED   KIND
apiserversources  sources.knative.dev           true         ApiServerSource
containersources  sources.knative.dev           true         ContainerSource
pingsources       sources.knative.dev           true         PingSource
sinkbindings      sources.knative.dev           true         SinkBinding
----

Let's see how a simple source, the *PingSource* looks like : 

.link:{github-repo}/{eventing-repo}/eventinghello-source.yaml[eventinghello-source.yaml]
[source,yaml,subs="attributes+,+macros"]
----
apiVersion: sources.knative.dev/v1
kind: PingSource #<1>
metadata:
  name: eventinghello-ping-source
spec: #<2>
  schedule: "*/2 * * * *"
  data: '{"key": "every 2 mins"}'
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: eventinghello
----

<1> The type of event source, the eventing system deploys a bunch of sources out of the box and it also provides way to deploy custom resources
<2> spec will be unique per source, per kind

[#eventing-sink]
== Referencing the Event Sink

*Knative Eventing Sink* is how you specify the event receiver -- that is the consumer of the event--. Sinks can be invoked directly in a point-to-point fashion by referencing them via the Event Source's `sink` as shown below:

.link:{github-repo}/{eventing-repo}/eventinghello-source.yaml[eventinghello-source.yaml]
[source,yaml,subs="attributes+,+macros"]
----
apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: eventinghello-ping-source
spec:
  schedule: "*/2 * * * *"
  data: '{"message": "Thanks for doing Knative Tutorial"}'
  sink:  #<1>
    ref:
      apiVersion: serving.knative.dev/v1 #<2>
      kind: Service
      name: eventinghello #<3>
----

<1> sink can target any Kubernetes Service or 
<2> a Knative Service
<3> Deployed as "eventinghello"

[NOTE]
====
Event Source can define the attributes that it wishes to receive via the 
spec.  In the above example it defines **schedule**(the cron expression) and **jsonData** that will be sent as part of the event.

When you xref:{eventing-repo}#eventing-watch-logs[watch logs], you will notice this data being delivered to the service.
====

[#eventing-sink-service]
== Create Sink Service 

Run the following command to create the Knative service that will be used as the subscriber for the cron events:

.link:{github-repo}/{eventing-repo}/eventing-hello-sink.yaml[eventing-hello-sink.yaml]
[source,yaml,subs="attributes+,+macros"]
----
include::eventing:example$eventing/eventing-hello-sink.yaml[]
----

:service-file: eventing-hello-sink.yaml
[#eventing-deploy-sink-service]
=== Deploy Sink Service

Run the following commands to create the service:

include::eventing:partial$deploy-knative-resources.adoc[tags=tab-1;eventing-hello;tab-2]

:service-file: eventinghello-source.yaml
[#eventing-create-event-source]
== Create Event Source

Run the following commands to create the event source resources:

include::eventing:partial$deploy-knative-resources.adoc[tags=tab-1;eventing-hello-source;tab-2]

[#eventing-verify-event-source]
== Verification

[tabs]
====
kn::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kn source ping list -n {tutorial-namespace}
----

Running  the above command should return the following result:

[.console-output]
[source,bash]
----
NAME                        SCHEDULE      SINK                 AGE   CONDITIONS   READY   REASON
eventinghello-ping-source   */2 * * * *   ksvc:eventinghello   99s   4 OK / 4     True
----

--
{kubernetes-cli}::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n {tutorial-namespace} get \
  pingsources.sources.knative.dev \
  eventinghello-ping-source
----

Running  the above command should return the following result:

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
NAME                        SINK                                                     AGE   READY   REASON
eventinghello-ping-source   http://eventinghello.knativetutorial.svc.cluster.local   47s   True
----
--
====

If you haven't already, you can xref:{eventing-repo}#eventing-watch-logs[watch logs] to see the ping job source sending an event every 2 minutes:

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
stern eventinghello -c user-container -n {tutorial-namespace} 
----

[.console-output]
[source,bash,subs="quotes"]
----
...
eventinghello-2m4hn-deployment-c8f4f6758-qrjm6 user-container 2021-01-28 08:14:05,427 INFO  [eventing-hello] (executor-thread-1) ce-id=4b59c201-56a3-4189-b042-4246d3f33504
eventinghello-2m4hn-deployment-c8f4f6758-qrjm6 user-container 2021-01-28 08:14:05,501 INFO  [eventing-hello] (executor-thread-1) ce-source=/apis/v1/namespaces/user2-knativetutorial/pingsources/eventinghello-ping-source
eventinghello-2m4hn-deployment-c8f4f6758-qrjm6 user-container 2021-01-28 08:14:05,501 INFO  [eventing-hello] (executor-thread-1) ce-specversion=1.0
eventinghello-2m4hn-deployment-c8f4f6758-qrjm6 user-container 2021-01-28 08:14:05,501 INFO  [eventing-hello] (executor-thread-1) ce-time=2021-01-28T08:14:00.000224506Z
eventinghello-2m4hn-deployment-c8f4f6758-qrjm6 user-container 2021-01-28 08:14:05,502 INFO  [eventing-hello] (executor-thread-1) ce-type=dev.knative.sources.ping
eventinghello-2m4hn-deployment-c8f4f6758-qrjm6 user-container 2021-01-28 08:14:05,502 INFO  [eventing-hello] (executor-thread-1) content-type=application/json
eventinghello-2m4hn-deployment-c8f4f6758-qrjm6 user-container 2021-01-28 08:14:05,502 INFO  [eventing-hello] (executor-thread-1) content-length=47
#eventinghello-2m4hn-deployment-c8f4f6758-qrjm6 user-container 2021-01-28 08:14:05,502 INFO  [eventing-hello] (executor-thread-1) POST:{"message":"Thanks for doing Knative Tutorial"}#
eventinghello-2m4hn-deployment-c8f4f6758-qrjm6 user-container I> No access restrictor found, access to any MBean is allowed
eventinghello-2m4hn-deployment-c8f4f6758-qrjm6 user-container Jolokia: Agent started with URL https://10.129.4.97:8778/jolokia/
----


[#eventing-cleanup]
== Cleanup

[tabs]
====
kn::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kn source ping delete -n {tutorial-namespace} eventinghello-ping-source 
kn service delete -n {tutorial-namespace} eventinghello
----
--
{kubernetes-cli}::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
{kubernetes-cli} -n {tutorial-namespace} delete -f pass:[${TUTORIAL_HOME}]/eventing/eventinghello-source.yaml
{kubernetes-cli} -n {tutorial-namespace} delete -f pass:[${TUTORIAL_HOME}]/eventing/eventing-hello-sink.yaml
----
--
====

