[[brokers-and-triggers]]
= Brokers and Triggers 
include::_attributes.adoc[]

:greeter-image: quay.io/rhdevelopers/knative-tutorial-greeter:quarkus
:service-file: default-broker.yaml

Use the Knative Eventing `Broker` and `Trigger` Custom Resources to allow for link:https://cloudevents.io/[CloudEvent] attribute filtering.

[#broker]
== Broker

.link:{github-repo}/{eventing-repo}/default-broker.yaml[default-broker]
[source,yaml,subs="attributes+,+macros"]
----
---
apiVersion: eventing.knative.dev/v1
kind: broker
metadata:
 name: default
----

include::eventing:partial$deploy-knative-resources.adoc[tags=tab-1;broker;tab-2]

Verify the created resources:

include::eventing:partial$knative-objects.adoc[tags=knative-eventing-broker]


[#install-kn-event-plugin]
== Install the kn event plugin

In the following we will use the https://github.com/knative-sandbox/kn-plugin-event[kn-event plugin] of the Knative CLI
to send CloudEvents to our broker.

[tabs]
====
Manual::
+
--
In order to make the `event` command available to `kn`, download the https://github.com/knative-sandbox/kn-plugin-event/releases[event plugin binary], and move it to `~/.config/kn/plugins/` or create a symlink to that location, and make sure it has executable permissions. On Linux you would do something like this:

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
mv /path/to/kn-event-linux-amd64 ~/.config/kn/plugins/kn-event
chmod +x ~/.config/kn/plugins/kn-event
----

--
Homebrew::
+
--
To install the plugin with Homebrew, just run this command:
[.console-output]
[source,bash]
----
brew install knative-sandbox/kn-plugins/event
----
--
====

You can then verify the plugin setup by displaying its help page:

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kn event -h
----

[.console-output]
[source,bash,subs="+quotes,+attributes,+macros"]
----
Manage CloudEvents from command line. Perform, easily, tasks like sending,
building, and parsing, all from command line.

Usage:
  event [command]

Aliases:
  event, kn event

Available Commands:
  build       Builds a CloudEvent and print it to stdout
  completion  Generate the autocompletion script for the specified shell
  help        Help about any command
  send        Builds and sends a CloudEvent to recipient
  version     Prints the kn event plugin version

Flags:
      --cluster string      name of the kubeconfig cluster to use
      --context string      name of the kubeconfig context to use
  -h, --help                help for event
      --kubeconfig string   kubectl configuration file (default: ~/.kube/config)
  -o, --output output       Output format. One of: human|json|yaml. (default human)
  -v, --verbose             verbose output

Use "event [command] --help" for more information about a command.
----

[#eventing-service]
== Service 

Now, that you have the broker configured, you need to create the sinks `eventingaloha` and `eventingbonjour`, which will receive the filtered events.

.link:{github-repo}/{eventing-repo}/eventing-aloha-sink.yaml[eventing-aloha-sink.yaml]
[source,yaml,subs="attributes+,+macros"]
----
include::eventing:example$eventing/eventing-aloha-sink.yaml[]
----

.link:{github-repo}/{eventing-repo}/eventing-bonjour-sink.yaml[eventing-bonjour-sink.yaml]
[source,yaml,subs="attributes+,+macros"]
----
include::eventing:example$eventing/eventing-bonjour-sink.yaml[]
----

[NOTE]
====
The image being used by both of these services is identical.  However, the difference in name `aloha` vs `bonjour` will make obvious which one is receiving a particular event.
====

[#eventing-deploy-service]
=== Deploy Service

Run the following commands to deploy the `eventingaloha` and `eventingbonjour` services:

:service-file: eventing-aloha-sink.yaml
:sink-service-name: eventingaloha
:revision-name: eventingaloha-v1
==== Deploy Aloha
include::eventing:partial$deploy-knative-resources.adoc[tags=tab-1;eventing-hello-sink;tab-2]

:service-file: eventing-bonjour-sink.yaml
:sink-service-name: eventingbonjour
:revision-name: eventingbonjour-v1
==== Deploy Bonjour
include::eventing:partial$deploy-knative-resources.adoc[tags=tab-1;eventing-hello-sink;tab-2]

Wait approximately 60 seconds for `eventingaloha` and `eventingbonjour` to terminate, scale-down to zero before proceeding.

[#eventing-trigger]
== Trigger

Now create the the trigger for `eventingaloha` that will associate the filtered events to a service:

.link:{github-repo}/{eventing-repo}/trigger-helloaloha.yaml[trigger-helloaloha.yaml]
[source,yaml]
----
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: helloaloha
spec:
  broker: default
  filter:
    attributes:
      type: aloha # <1>
  subscriber:
    ref:
     apiVersion: serving.knative.dev/v1
     kind: Service
     name: eventingaloha
----

<1> The `type` is the CloudEvent type that is mapped to the `ce-type` HTTP header.  A Trigger can filter by link:https://cloudevents.io/[CloudEvent] attributes such as type, source or extension.

Now create the the trigger for `eventingaloha` that will associate the filtered events to a service:

:service-file: trigger-helloaloha.yaml
:trigger-name: helloaloha
:trigger-sub-name: eventingaloha
:trigger-event: aloha
=== Create Aloha Trigger
include::eventing:partial$deploy-knative-resources.adoc[tags=tab-1;eventing-trigger-sub;tab-2]

:service-file: trigger-hellobonjour.yaml
:trigger-name: hellobonjour
:trigger-sub-name: eventingbonjour
:trigger-event: bonjour
=== Create Bonjour Trigger
Now create the the trigger for `eventingbonjour` that will associate the filtered events to a service:

.link:{github-repo}/{eventing-repo}/trigger-hellobonjour.yaml[trigger-hellobonjour.yaml]
[source,yaml,linenums,subs="attributes+,+macros"]
----
include::eventing:example$eventing/trigger-hellobonjour.yaml[]
----

Run the following commands to create the trigger:

include::eventing:partial$deploy-knative-resources.adoc[tags=tab-1;eventing-trigger-sub;tab-2]

Verify that your triggers are ready:

include::eventing:partial$knative-objects.adoc[tag=knative-triggers]

[#eventing-trigger-verification]
== Verification

Pull out the subscriberUri for `eventhingaloha`:

[#eventing-triggers-verify-sub1]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl get trigger helloaloha -o jsonpath='{.status.subscriberUri}'
----

The command should show the output as: 
[.console-output]
[source,bash]
----
http://eventingaloha.knativetutorial.svc.cluster.local
----

Pull out the subscriberUri for `eventhingbonjour`:

[#eventing-triggers-verify-sub2]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl get trigger hellobonjour -o jsonpath='{.status.subscriberUri}'
----

The command should show the output as: 
[.console-output]
[source,bash]
----
http://eventingbonjour.knativetutorial.svc.cluster.local
----

As well as broker's subscriberUri:

[#eventing-triggers-verify-sub3]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl get broker default -o jsonpath='{.status.address.url}'
----

The command should show the output as: 
[.console-output]
[source,bash]
----
http://broker-ingress.knative-eventing.svc.cluster.local/{tutorial-namespace}/default
----

You should notice that the subscriberURIs are Kubernetes services with the suffix of `{tutorial-namespace}.svc.cluster.local`.  This means they can be interacted with from another pod within the Kubernetes cluster.

Now that you have setup the Broker and Triggers you need to send in some test messages to see the behavior.

[#send-events]
=== Send events to the Broker
First start streaming the logs for the event consumers:

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
stern eventing -c user-container
----

(NB: the argument of the command `stern` is an expression, so it matches both services `eventingaloha` and `eventingbonjour`.)

We will now send a CloudEvent of type `aloha` to the broker:

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kn event send -t aloha -f origin="from kn-event" \
  --to Broker:eventing.knative.dev/v1:default
----

You will then see `eventingaloha` will scale-up to respond to that event:

[#trigger-watch-aloha-scale]
[.console-input]
[source,bash,subs="+macros,+attributes"]
-----
watch kubectl get pods
-----

The command above should show the following output:

[.console-output]
[source,bash]
-----
NAME                                        READY STATUS  AGE
eventingaloha-1-deployment-6cdc888d9d-9xnnn 2/2   Running 30s
-----

Next, send another event, this time of type `bonjour`:

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kn event send -t bonjour -f origin="from kn-event" \
  --to Broker:eventing.knative.dev/v1:default
----

And you will see the `eventingbonjour` pod scale up:

[#trigger-watch-eventingbonjour-scale]
[.console-input]
[source,bash,subs="+macros,+attributes"]
-----
watch kubectl get pods
-----

The command above should show the following output:

[.console-output]
[source,bash]
-----
NAME                                         READY STATUS  AGE
eventingbonjour-1-deployment-fc7858b5b-s9prj 2/2   Running 5s
-----

In the previous examples you sent to the broker a payload configured with CloudEvent types `aloha` and `bonjour`, respectively.
Each trigger filtered the incoming message and sent it to the configured Sink Service in case of a match.

You can experiment by using different type filters in the Subscription to see how the different subscribed services respond.
`Filters` may use an link:https://cloudevents.io/[CloudEvent] attribute for its criteria.

[#eventing-cleanup]
== Cleanup

[tabs]
====
kn::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kn service delete eventingbonjour 
kn service delete eventingaloha 
kn trigger delete helloaloha
kn trigger delete hellobonjour 
kn broker delete default 
----
--
{kubernetes-cli}::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl delete -f eventing-aloha-sink.yaml
kubectl delete -f eventing-bonjour-sink.yaml
kubectl delete -f trigger-helloaloha.yaml
kubectl delete -f trigger-hellobonjour.yaml
kubectl delete -f default-broker.yaml
----
--
====

