apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-and-list-target
spec:
  inputs:
    resources:
      - name: source
        type: git
    params:
      - name: contextDir
        description: "The context directory within the repository for sources"
        default: apps/greeter/java/quarkus
  outputs: {}
  stepTemplate:
    resources:
      limits:
        cpu: 1
        memory: 2Gi
    securityContext:
      allowPrivilegeEscalation: false
      privileged: false
      # the default underprivileged user to be used
      runAsUser: 10001
  steps:
    - name: maven-build
      image: quay.io/rhdevelopers/tutorial-tools:0.0.2
      workingDir: "/workspace/source/$(inputs.params.contextDir)"
      args:
        - mvn
        - -DskipTests
        - clean
        - package
    - name: ls-target
      image: busybox
      command: ['ls','-ltr', "/workspace/source/$(inputs.params.contextDir)/target"]