FROM quay.io/rhdevelopers/tutorial-tools

# Uncomment two lines below to allow maven builds from docker cotainer use 
# the maven repository manager for all maven builds
# ENV MAVEN_MIRROR_URL http://192.168.1.102:8081/nexus/content/groups/public/
# RUN /usr/local/bin/entrypoint-run.sh 'mvn -v'

EXPOSE 8080
