== Setup

[#prerequisite]
=== Prerequisite CLI tools

You will need in this tutorial:

[cols="3*^,3*."]
|===
|**Tool** |**macOS** |**Fedora**
| `minishift` 
| https://github.com/minishift/minishift/releases
| https://github.com/minishift/minishift/releases

| docker
| https://www.docker.com/docker-mac[Docker for Mac]
| `dnf install docker`

| https://kubernetes.io/docs/tasks/tools/install-kubectl[kubectl]
| https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl-binary-via-curl[Mac OS]
| `dnf install kubernetes-client` 

| https://maven.apacge.org[Apache Maven]
| `brew install maven`
| `dnf install maven`

| https://github.com/wercker/stern[stern]
| `brew install stern`
| `sudo curl --output /usr/local/bin/stern -L https://github.com/wercker/stern/releases/download/1.6.0/stern_linux_amd64 && sudo chmod +x /usr/local/bin/stern`

| `curl`, `gunzip`, `tar` 
| built-in or part of your bash shell
| should also be installed already, but just in case... `dnf install curl gzip tar`

| git
| `brew install git`
| `dnf install git`

| http://xmlstar.sourceforge.net/[xmlstarlet]
| `brew install xmlstarlet`
| http://xmlstar.sourceforge.net/

| https://github.com/mikefarah/yq[yq]
| `brew install yq`
|  https://github.com/mikefarah/yq/releases/latest

| https://httpie.org/[httpie]
| `brew install httpie`
| `dnf install httpie`

| https://golang.org[go]
| `brew install golang`
| https://dl.google.com/go/go1.11.5.linux-amd64.tar.gz

| https://github.com/rakyll/hey[hey]
| `go get -u github.com/rakyll/hey`
| `go get -u github.com/rakyll/hey`

| https://jsonnet.org/
|`brew install jsonnet`
| https://github.com/google/jsonnet
|===

[#download-tutorial-sources]
=== Download Tutorial Sources
Before we start to setting up the environment, lets clone the tutorial sources and call the cloned folder as `$TUTORIAL_HOME`

[source,bash]
----
git clone https://github.com/kameshsampath/knative-tutorial
----

The `work` folder in `$TUTORIAL_HOME` can be used to download the demo application resources and refer them during the exercises. The `work` folder has a README, which has instructions on source code repo and git commands to clone the sources.

[IMPORTANT]
====
All examples in this tutorial are tested with **OpenShift 3.11** and **Knative 0.3.0** 
====

[#minishift]
=== Minishift

All the demos in this tutorial will be run using https://github.com/minishift/minishift[minishift], the single node https://www.okd.io/[OKD](the Origin Community Distribution of kubernetes that powers Red Hat OpenShift) cluster that can be used for development purposes. 

==== Setup minishift

[source,bash,linenums]
-----
export TIMEZONE=$(sudo systemsetup -gettimezone | awk '{print $3}') #<1>
minishift profile set knative-tutorial
minishift config set openshift-version v3.11.0
minishift config set memory 8GB # if you more then preferred is 10GB
minishift config set cpus 4
minishift config set disk-size 50g
minishift config set image-caching true
minishift addons enable admin-user

minishift start --timezone $TIMEZONE 

eval $(minishift docker-env) && eval $(minishift oc-env)
-----

<1> Some examples we use in this tutorial are time sensitive, hence its recommended to set the appropriate timezone. If you are linux please use the appropriate command to get the timezone of the host.

[#admission-controller-webhook]
=== Enable Admission Controller Webhook 
[source,bash,linenums]
----
#!/bin/bash

minishift openshift config set --target=kube --patch '{
  "admissionConfig": {
    "pluginConfig": {
      "ValidatingAdmissionWebhook": {
        "configuration": {
          "apiVersion": "apiserver.config.k8s.io/v1alpha1",
          "kind": "WebhookAdmission",
          "kubeConfigFile": "/dev/null"
        }
      },
      "MutatingAdmissionWebhook": {
        "configuration": {
          "apiVersion": "apiserver.config.k8s.io/v1alpha1",
          "kind": "WebhookAdmission",
          "kubeConfigFile": "/dev/null"
        }
      }
    }
  }
}'

# Allowing few minutes for the OpenShift to be restarted
until oc login -u admin -p admin 2>/dev/null; do sleep 5; done;
----

[#setup-knative]
=== Knative Setup

[#login-as-admin]
==== Login as admin user

Since there was an `admin` addon added during minishift configuration, its now possible to login with the `admin` user. For example:

[source,bash]
----
oc login -u admin -p admin
----

[#install-istio]
==== Install Istio

[#istio-policies]
===== Configure Istio Policies
Knative depends on Istio, to deploy Istio you need to run the following commands to configure necessary https://istio.io/docs/setup/kubernetes/platform-setup/openshift/[privileges] to the service accounts used by Istio.

[source,bash,linenums]
----
oc adm policy add-scc-to-user anyuid -z istio-ingress-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z default -n istio-system
oc adm policy add-scc-to-user anyuid -z prometheus -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-egressgateway-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-citadel-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-ingressgateway-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-cleanup-old-ca-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-mixer-post-install-account -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-mixer-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-pilot-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-sidecar-injector-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z cluster-local-gateway-service-account -n istio-system
oc adm policy add-scc-to-user anyuid -z istio-galley-service-account -n istio-system

----

[#deploy-istio]
===== Deploy Istio Components

[source,bash,linenums]
----
curl -L https://github.com/knative/serving/releases/download/v0.3.0/istio.yaml \
  | sed 's/LoadBalancer/NodePort/' \
  | kubectl apply --filename -
----

NOTE: The above command throws some warnings and error as to some objects not found, it can safely ignore or run the command again

You can moinitor the Istio components via the command:
[source,bash]
----
oc get pods -n istio-system -w
----

NOTE: It will take a few minutes for all the Istio components to be up and running. Please wait for all the Istio pods to be running before deploying <<install-knative-serving,Knative Serving>>.  Use kbd:[CTRL+C] to exit watch mode. 

A successful deployment should show similar output as shown below.

[source,bash,linenums]
----
$ oc get pods -n istio-system
NAME                                        READY     STATUS      RESTARTS   AGE
cluster-local-gateway-76db55c785-9f7zc      1/1       Running     0          2m
istio-citadel-746c765786-fqx8m              1/1       Running     0          2m
istio-cleanup-secrets-znzc6                 0/1       Completed   0          2m
istio-egressgateway-7b46794587-m6tqm        1/1       Running     0          2m
istio-galley-75c6976d79-bcnbp               1/1       Running     0          2m
istio-ingressgateway-57f76dc4db-85cps       1/1       Running     0          2m
istio-pilot-6495978c49-6jrmf                2/2       Running     0          2m
istio-pilot-6495978c49-7l6w7                2/2       Running     0          2m
istio-pilot-6495978c49-fh9n8                2/2       Running     0          2m
istio-policy-6677c87b9f-7wxxj               2/2       Running     0          2m
istio-sidecar-injector-879fd9dfc-82wjl      1/1       Running     0          2m
istio-statsd-prom-bridge-549d687fd9-mlnb2   1/1       Running     0          2m
istio-telemetry-7d46d668db-4qwz5            2/2       Running     0          2m
----


[#update-istio-sidecar-injector-configmap]
===== Update Istio sidecar injector ConfigMap

The Istio v1.0.1 release automatic sidecar injection has removed `privileged:true` from init contianers,this will cause the Pods with istio proxies automatic inject to crash. Run the following command to update the **istio-sidecar-injector** ConfigMap.

The following command ensures that the `privileged:true` is added to the **istio-sidecar-injector** ConfigMap:

[source,bash]
----
oc apply -n istio-system -f $TUTORIAL_HOME/patches/istio-sidecar-injector.yaml
----

IMPORTANT: Run the above command only once per minishift instance

[#install-knative-build]
==== Install Knative Build
[source,bash,linenums]
----
# Setup Knative Build Policies
oc adm policy add-scc-to-user anyuid -z build-controller -n knative-build
oc adm policy add-scc-to-user anyuid -z build-controller -n knative-build

# Install Knative Build components
kubectl apply --filename https://github.com/knative/build/releases/download/v0.3.0/release.yaml

# give cluster admin privileges to Service Account Build Controller on project knative-build
oc adm policy add-cluster-role-to-user cluster-admin -z build-controller -n knative-build
oc adm policy add-cluster-role-to-user cluster-admin -z build-controller -n knative-build
----

[source,bash]
----
oc get pods -n knative-build -w
----

NOTE: It will take a few minutes for all the Knative Build components to be up and running. Use kbd:[CTRL+C] to exit watch mode. 

A successful deployment should show similar output as shown below.

[source,bash,linenums]
----
$ oc get pods -n knative-build
NAME                                READY     STATUS    RESTARTS   AGE
build-controller-79cb969d89-bnzbr   1/1       Running   0          28s
build-webhook-58d685fc58-f5s4l      1/1       Running   0          27s
----

[#install-knative-serving]
==== Install Knative Serving

[source,bash,linenums]
----
# Setup Knative Serving Policies
oc adm policy add-scc-to-user anyuid -z controller -n knative-serving
oc adm policy add-scc-to-user anyuid -z autoscaler -n knative-serving

# Install Knative Serving components
curl -L https://github.com/knative/serving/releases/download/v0.3.0/serving.yaml \
  | sed 's/LoadBalancer/NodePort/' \
  | kubectl apply --filename -

# give cluster admin privileges to Service Account Controller on project knative-serving
oc adm policy add-cluster-role-to-user cluster-admin -z controller -n knative-serving

----

You can monitor the Knative Serving components via  components via the command:
[source,bash]
----
oc get pods -n knative-serving -w
----

NOTE: It will take a few minutes for all the Knative Serving components to be up and running. Use kbd:[CTRL+C] to exit watch mode. 

A successful deployment should show similar output as shown below.

[source,bash,linenums]
----
$ oc get pods -n knative-serving
NAME                          READY     STATUS    RESTARTS   AGE
activator-598b4b7787-sb9gv    2/2       Running   0          35s
autoscaler-5cf5cfb4dc-9zd7p   2/2       Running   0          34s
controller-7fc84c6584-ggp7b   1/1       Running   0          38s
webhook-7797ffb6bf-swr4c      1/1       Running   0          38s
----

[#install-knative-eventing]
==== Install Knative Eventing

[source,bash,linenums]
----
# Setup Knative Eventing Policies
oc adm policy add-scc-to-user anyuid -z eventing-controller -n knative-eventing
oc adm policy add-scc-to-user anyuid -z in-memory-channel-dispatcher -n knative-eventing
oc adm policy add-scc-to-user anyuid -z in-memory-channel-controller -n knative-eventing

# Install Knative Eventing components
kubectl apply --filename https://github.com/knative/eventing/releases/download/v0.3.0/release.yaml
kubectl apply --filename https://github.com/knative/eventing-sources/releases/download/v0.3.0/release.yaml

# give cluster admin privileges to Service Accounts on project knative-eventing
oc adm policy add-cluster-role-to-user cluster-admin -z eventing-controller -n knative-eventing
oc adm policy add-cluster-role-to-user cluster-admin -z default -n knative-sources
oc adm policy add-cluster-role-to-user cluster-admin -z in-memory-channel-dispatcher -n knative-eventing
oc adm policy add-cluster-role-to-user cluster-admin -z in-memory-channel-controller -n knative-eventing

----

You can monitor the Knative Eventing components via  components via the command:
[source,bash,linenums]
----
oc get pods -n knative-eventing -w
oc get pods -n knative-sources -w 
----

NOTE: It will take a few minutes for all the Knative Eventing components to be up and running. Use kbd:[CTRL+C] to exit watch mode.

[source,bash,linenums]
----
$ oc get pods -n knative-eventing
NAME                                            READY     STATUS    RESTARTS   AGE
eventing-controller-847d8cf969-zv77v            1/1       Running   0          1m
in-memory-channel-controller-59dd7cfb5b-s82x6   1/1       Running   0          1m
webhook-7cfff8d86d-4kljw                        1/1       Running   0          1m

$ oc get pods -n knative-sources
NAME                   READY     STATUS    RESTARTS   AGE
controller-manager-0   1/1       Running   0          1m
----

[#configure-openshift-project]
=== Configuring OpenShift project for Knative applications

[source,bash,linenums]
----
oc new-project knativetutorial
oc adm policy add-scc-to-user privileged -z default #<1>
oc adm policy add-scc-to-user anyuid -z default
----

<1> The `oc adm policy` adds the **privileged** https://docs.okd.io/3.10/admin_guide/manage_scc.html[Security Context Constraints(SCCs)]to the **default** Service Account. The SCCs are the precursor to the PSP (Pod Security Policy) mechanism in kubernetes.


[.text-center]
**(OR)**

[source,bash]
----
kubectl create namespace knativetutorial
----

[#setup-work-folder]
=== Work folder

The work folder i.e `$TUTORIAL_HOME/work` can be used as a work directory during the build. The README in the work folder as the GitHub repository links of the applications `greeter` and `event-greeter` that will be used in various exercises.
