#tag::knative-services[]

ifndef::workshop[]
[#knative-services]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n {tutorial-namespace}  get services.serving.knative.dev greeter 
----
copyToClipboard::knative-services[]

**(OR)**
endif::[]

[#oc-knative-services]
[source,bash,subs="+macros,+attributes"]
----
oc -n {tutorial-namespace}  get services.serving.knative.dev greeter 
----
copyToClipboard::oc-knative-services[]

#end::knative-services[]

#tag::knative-configs[]

ifndef::workshop[]
[#knative-configs]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n {tutorial-namespace} get configurations.serving.knative.dev greeter
----
copyToClipboard::knative-configs[]

**(OR)**
endif::[]

[#oc-knative-configs]
[source,bash,subs="+macros,+attributes"]
----
oc -n {tutorial-namespace} get configurations.serving.knative.dev greeter
----
copyToClipboard::oc-knative-configs[]

#end::knative-configs[]

#tag::knative-routes[]

ifndef::workshop[]
[#knative-routes]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n {tutorial-namespace} get routes.serving.knative.dev greeter
----
copyToClipboard::knative-routes[]

**(OR)**
endif::[]

[#oc-knative-routes]
[source,bash,subs="+macros,+attributes"]
----
oc -n {tutorial-namespace} get routes.serving.knative.dev greeter
----
copyToClipboard::oc-knative-routes[]

#end::knative-routes[]

#tag::knative-revisions[]
ifndef::workshop[]
[#knative-revisions]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n {tutorial-namespace} get rev -l serving.knative.dev/service=greeter --sort-by="{.metadata.creationTimestamp}"
----
copyToClipboard::knative-revisions[]

**(OR)**
endif::[]

[#oc-knative-revisions]
[source,bash,subs="+macros,+attributes"]
----
oc -n {tutorial-namespace} get rev -l serving.knative.dev/service=greeter --sort-by="{.metadata.creationTimestamp}"
----
copyToClipboard::oc-knative-revisions[]

#end::knative-revisions[]

#tag::knative-config-revisions[]
ifndef::workshop[]
[#knative-config-revisions]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n {tutorial-namespace} get rev -l serving.knative.dev/configuration=greeter --sort-by="{.metadata.creationTimestamp}"
----
copyToClipboard::knative-config-revisions[]

**(OR)**
endif::[]

[#oc-knative-config-revisions]
[source,bash,subs="+macros,+attributes"]
----
oc -n {tutorial-namespace} get rev -l serving.knative.dev/configuration=greeter --sort-by="{.metadata.creationTimestamp}"
----
copyToClipboard::oc-knative-config-revisions[]

#end::knative-config-revisions[]

#tag::knative-build[]

[#knative-build]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n {tutorial-namespace} get builds.build.knative.dev event-greeter-build
----
copyToClipboard::knative-build[]

**(OR)**

[#oc-knative-build]
[source,bash,subs="+macros,+attributes"]
----
oc -n {tutorial-namespace} get builds.build.knative.dev event-greeter-build
----
copyToClipboard::oc-knative-build[]

#end::knative-build[]

#tag::knative-build-templates[]

[#knative-build-templates]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n {tutorial-namespace} get buildtemplates.build.knative.dev build-java-maven
----
copyToClipboard::knative-build-templates[]

**(OR)**

[#oc-knative-build-templates]
[source,bash,subs="+macros,+attributes"]
----
oc -n {tutorial-namespace} get buildtemplates.build.knative.dev build-java-maven
----
copyToClipboard::oc-knative-build-templates[]

#end::knative-build-templates[]

#tag::knative-event-channel[]
ifndef::workshop[]
[#knative-event-channel]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n {tutorial-namespace} get channels.eventing.knative.dev ch-event-greeter
----
copyToClipboard::knative-event-channel[]

**(OR)**
endif::[]

[#oc-knative-event-channel]
[source,bash,subs="+macros,+attributes"]
----
oc -n {tutorial-namespace} get channels.eventing.knative.dev ch-event-greeter
----
copyToClipboard::oc-knative-event-channel[]

#end::knative-event-channel[]

#tag::knative-event-cronjob-sources[]
ifndef::workshop[]
[#knative-event-sources]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n {tutorial-namespace} get cronjobsources.sources.eventing.knative.dev  event-greeter-cronjob-source
----
copyToClipboard::knative-event-sources[]

**(OR)**
endif::[]

[#oc-knative-event-sources]
[source,bash,subs="+macros,+attributes"]
----
oc -n {tutorial-namespace} get cronjobsources.sources.eventing.knative.dev event-greeter-cronjob-source
----
copyToClipboard::oc-knative-event-sources[]

#end::knative-event-cronjob-sources[]

#tag::knative-event-subscribers[]
ifndef::workshop[]
[#knative-event-subscribers]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n {tutorial-namespace} get subscriptions.eventing.knative.dev event-greeter-subscriber
----
copyToClipboard::knative-event-subscribers[]

**(OR)**
endif::[]

[#oc-knative-event-subscribers]
[source,bash,subs="+macros,+attributes"]
----
oc -n {tutorial-namespace} get subscriptions.eventing.knative.dev event-greeter-subscriber
----
copyToClipboard::oc-knative-event-subscribers[]

#end::knative-event-subscribers[]

#tag::knative-event-services[]
ifndef::workshop[]
[#knative-services]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n {tutorial-namespace}  get services.serving.knative.dev event-greeter  
----
copyToClipboard::knative-services[]

**(OR)**
endif::[]

[#oc-knative-services]
[source,bash,subs="+macros,+attributes"]
----
# get a Knative Service (short name ksvc) called greeter
oc -n {tutorial-namespace}  get services.serving.knative.dev event-greeter 
----
copyToClipboard::oc-knative-services[]


#end::knative-event-services[]
