[#install-knative-minikube]
=== Install with Minikube

[#start-minikube]
==== Configure and Start Minikube

Before installing Knative and its components, we need to create a Minikube virtual machine and deploy Kubernetes into it:

[[setup-minikube-start]]
[source,bash,subs="+macros,+attributes"]
----
minikube profile knative #<1>

minikube start -p knative --memory=8192 --cpus=4 \#<2> 
  --kubernetes-version=v1.12.0 \#<3> 
  --vm-driver=hyperkit \#<4>  
  --disk-size=50g \
  --extra-config=apiserver.enable-admission-plugins="LimitRanger,NamespaceExists,NamespaceLifecycle,ResourceQuota,ServiceAccount,DefaultStorageClass,MutatingAdmissionWebhook"
----
copyToClipboard::setup-minikube-start[]

<1> Setting Minikube profile to **knative** so that all future Minikube commands are executed with this profile context
<2> Starting a profile named **knative**
<3> Minimum Kubernetes version needs to be 1.12, refer to issue https://github.com/knative/serving/issues/3067 for more details.
<4> On macOS. On Linux, please use `--vm-driver=kvm2`


[#install-knative-istio]
==== Install Istio 

[#run-install-istio]
[source,bash,subs="+macros,+attributes"]
----
kubectl apply --filename {knative-serving-repo}/{knative-serving-version}/istio-crds.yaml && \
kubectl apply --filename {knative-serving-repo}/{knative-serving-version}/istio.yaml
----
copyToClipboard::run-install-istio[]

[NOTE,subs="+macros,+attributes"]
====
Installation of Istio components will take some time and it is highly recommended that you start Knative components installation only after you have verified that all Istio component pods are running. The Istio pods can be watched using the command:

[#setup-watch-istio-pods]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n istio-system get pods -w 
----
copyToClipboard::setup-watch-istio-pods[]

You can use kbd:[CTRL + c ] to terminate the watch
====

A successful Istio install will have the pods running in the `istio-system` namespace as shown below:

[source,bash]
----
NAME                                       READY   STATUS      RESTARTS   AGE
cluster-local-gateway-547467ccf6-857mx     1/1     Running     0          6h35m
istio-citadel-7d64db8bcf-xgdh7             1/1     Running     0          6h35m
istio-cleanup-secrets-7mjbl                0/1     Completed   0          6h35m
istio-egressgateway-6ddf4c8bd6-sglg6       1/1     Running     0          6h35m
istio-galley-7dd996474-4jhr4               1/1     Running     0          6h35m
istio-ingressgateway-84b89d647f-f9n4h      1/1     Running     0          6h35m
istio-pilot-86bb4fcbbd-ptz7n               2/2     Running     0          6h35m
istio-pilot-86bb4fcbbd-s9qxl               2/2     Running     0          6h34m
istio-pilot-86bb4fcbbd-xd887               2/2     Running     0          6h34m
istio-policy-5c4d9ff96b-tzkbw              2/2     Running     0          6h35m
istio-security-post-install-xdxc7          0/1     Completed   0          6h35m
istio-sidecar-injector-6977b5cf5b-9wsjw    1/1     Running     0          6h35m
istio-telemetry-7676df547f-55p6c           2/2     Running     0          6h35m
----

[#install-knative-serving]
===== **Install Knative Serving**

[#run-install-knative-serving]
[source,bash,subs="+macros,+attributes"]
----
kubectl apply --filename {knative-serving-repo}/{knative-serving-version}/serving.yaml
----
copyToClipboard::run-install-knative-serving[]

[NOTE]
====
As the Knative serving components are getting installed, you can watch their status using the following command:

[#setup-watch-knative-serving-pods]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n knative-serving get pods -w 
----
copyToClipboard::setup-watch-knative-serving-pods[]

You can use kbd:[CTRL + c ] to terminate the watch
====

A successful Knative serving installation will have its pods running in the `knative-serving` namespace as shown below:

[source,bash]
----
NAME                          READY   STATUS    RESTARTS   AGE
activator-69b8474d6b-fhnwq    2/2     Running   0          6h33m
autoscaler-6579b57774-lcjd2   2/2     Running   0          6h33m
controller-66cd7d99df-6lt2t   1/1     Running   0          6h33m
webhook-6d9568d-htxlt         1/1     Running   0          6h33m
----

[#install-knative-build]
===== **Install Knative Build** 

[#run-install-knative-build]
[source,bash,subs="+macros,+attributes"]
----
kubectl apply --filename {knative-build-repo}/{knative-build-version}/build.yaml
----
copyToClipboard::run-install-knative-build[]

[NOTE,subs="+macros,+attributes"]
====
As the Knative build components are getting installed, you can watch their status using the following command:

[#setup-watch-knative-build-pods]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n knative-build get pods -w 
----
copyToClipboard::setup-watch-knative-build-pods[]

You can use kbd:[CTRL + c ] to terminate the watch
====

A successful Knative build installation will have its pods running in the `knative-build` namespace as shown below:

[source,bash]
----
NAME                                READY   STATUS    RESTARTS   AGE
build-controller-658d64d9bd-4m7l9   1/1     Running   0          6h32m
build-webhook-6bb747665f-trjxg      1/1     Running   0          6h32m
----

[#install-knative-eventing]
===== **Install Knative Eventing** 

[#run-install-knative-eventing]
[source,bash,subs="+macros,+attributes"]
----
kubectl apply --filename {knative-eventing-repo}/{knative-eventing-version}/release.yaml && \
kubectl apply --filename {knative-sources-repo}/{knative-sources-version}/eventing-sources.yaml && \
kubectl apply --filename https://raw.githubusercontent.com/knative/serving/{knative-serving-version}/third_party/config/build/clusterrole.yaml
----
copyToClipboard::run-install-knative-eventing[]

[NOTE,subs="+macros,+attributes"]
====
As the Knative eventing components are getting installed, you can watch their status using the following commands:

.Event Sources
[#setup-watch-knative-sources-pods]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n knative-sources get pods -w 
----
copyToClipboard::setup-watch-knative-sources-pods[]

.Eventing
[#setup-watch-knative-eventing-pods]
[source,bash,subs="+macros,+attributes"]
----
kubectl -n knative-eventing get pods -w 
----
copyToClipboard::setup-watch-knative-eventing-pods[]

You can use kbd:[CTRL + c ] to terminate the watch
====

A successful Knative eventing installation will have the following pods running in the `knative-eventing` and `knative-sources` namespaces:

.knative-eventing namespace

[source,bash]
----
NAME                                            READY   STATUS    RESTARTS   AGE
eventing-controller-cfbb757bd-lg5zk             1/1     Running   0          6h35m
in-memory-channel-controller-75d6cc4b77-f8bfl   1/1     Running   0          6h35m
in-memory-channel-dispatcher-c89db8bb8-ktr26    2/2     Running   1          6h35m
webhook-5fbb8dbcc7-gk6cx                        1/1     Running   0          6h35m
----

.knative-sources namespace

[source,bash]
----
NAME                   READY   STATUS    RESTARTS   AGE
controller-manager-0   1/1     Running   0          6h35m
----

[#set-knative-tutorial-ns]
==== Configuring Kubernetes namespace

We will use a non default Kubernetes namespace called `{tutorial-namespace}` for all the tutorial exercises.

[#setup-knative-tutorial-ns]
[source,bash,subs="+macros,+attributes"]
----
kubectl create namespace {tutorial-namespace}
----
copyToClipboard::setup-knative-tutorial-ns[]

[TIP]
====
The kubens utility installed as part of https://github.com/ahmetb/kubectx[kubectx] allows for easy switching between Kubernetes namespaces.

[#setup-knative-tutorial-kubens]
[source,bash,subs="+macros,+attributes"]
----
kubens {tutorial-namespace}
----
copyToClipboard::setup-knative-tutorial-kubens[]

====
