[#install-knative-openshift]
=== OpenShift 

For OpenShift Knative installations we will use the OpenShift Cloud Function's https://github.com/openshift-cloud-functions/knative-operators[Knative Operators].

Clone the Knative Operator sources locally:

[source,bash,linenums]
-----
cd $TUTORIAL_HOME/work
git clone https://github.com/openshift-cloud-functions/knative-operators
cd knative-operators
-----

[#install-knative-ocp]
==== OCP

If you have an existing OpenShift cluster then run the following commands:

[source,bash,linenums]
-----
./etc/scripts/install.sh
-----

If you need more details about the installation or customizations refer https://github.com/openshift-cloud-functions/Documentation/blob/master/knative-OCP.md[Knative with OpenShift].

[#install-knative-minishift]
==== minishift

Run the following commands to configure Knative with minishift:

[source,bash,linenums]
-----
./etc/scripts/install-on-minishift.sh #<1>
-----

<1> It will create a minishift profile and install knative.  It also assumes that you already have minishift and your computer has 10GB or more of memory

[#configure-openshift-project]
==== Configuring OpenShift project for Knative applications

[source,bash,linenums]
----
oc new-project knativetutorial
oc adm policy add-scc-to-user privileged -z default #<1>
oc adm policy add-scc-to-user anyuid -z default
----

<1> The `oc adm policy` adds the **privileged** https://docs.okd.io/3.10/admin_guide/manage_scc.html[Security Context Constraints(SCCs)]to the **default** Service Account. The SCCs are the precursor to the PSP (Pod Security Policy) mechanism in kubernetes.