apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: blue-green-canary
spec:
  template:
    spec:
      containers:
        - image: quay.io/rhdevelopers/blue-green-canary
          env:
            - name: BLUE_GREEN_CANARY_COLOR
              value: "#6bbded"
            - name: BLUE_GREEN_CANARY_MESSAGE
              value: "Hello"
