apiVersion: eventing.knative.dev/v1alpha1
kind: Channel
metadata:
  name: genre-comedy
spec:
  provisioner:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: ClusterChannelProvisioner
    name: in-memory

---
apiVersion: eventing.knative.dev/v1alpha1
kind: Channel
metadata:
  name: genre-others
spec:
  provisioner:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: ClusterChannelProvisioner
    name: in-memory
