= Eventing
include::_attributes.adoc[]
ifdef::workshop[]
:greeter-container-image: quay.io/rhdevelopers/knative-tutorial-greeter:quarkus
:url: pass:[$SVC_URL]
:kube-ns: $WORKSHOP_USER-knativetutorial
endif::[]
ifndef::workshop[]
:greeter-container-image: dev.local/rhdevelopers/greeter:0.0.1 #<2>
:url: pass:[$IP_ADDRESS]
:kube-ns: knativetutorial
endif::[]
At the end of this chapter you will know and understand:

* What is an event source ?
* What is a channel ?
* What is a subscriber ?
* How to make a Knative serving service receive an event ?
* How to make a service a subscriber of an event ?

[#eventing-prerequisite]
== Prerequisite 
include::partial$prereq-cli.adoc[]

ifndef::workshop[]
[#eventing-assumptions]
== Assumptions

You have completed the xref:ROOT:{build-repo}/build.adoc[Build] or xref:ROOT:{build-repo}/build-templates.adoc[Build Templates], as you will be using the container image `greeter:0.0.1` or `greeter:0.0.2`  in this chapter.

[IMPORTANT,subs="marcos+,attributes+"]
====
Please ensure that you have set the needed environment variables as mentioned in xref:ROOT:{build-repo}/build.adoc#build-set-env[ Configure Environment Variables]
====
endif::[]

ifdef::workshop[]

include::partial$eventing-snippets.adoc[tag=eventing-nav-folder]

.Eventing Environment Variables
include::partial$build-env-vars.adoc[]

Create a new file called `setenv.sh` and add the following content to it:

[#eventing-set-env]
[source,bash,subs="+macros,+attributes"]
----
#!/bin/bash

# The Container Registry User Id
REGISTRY_USERNAME=${REGISTRY_USERNAME:-'<your-docker-repo-userid>'}
# The Container Registry User Password
REGISTRY_PASSWORD=${REGISTRY_PASSWORD:-'<your-docker-repo-user-password>'}
# The Container Registry URL, defaults to https://index.docker.io
REGISTRY_URL=${REGISTRY_URL:-'https://index.docker.io'}

# The Source repository Git  URL default  https://github.com/redhat-developer-demos/knative-tutorial-greeter.git
SOURCE_REPO_URL=${SOURCE_REPO_URL:-' https://github.com/redhat-developer-demos/knative-tutorial-greeter.git'}
# The Source revision defaults to master
SOURCE_REVISION=${SOURCE_REVISION:-'master'}
# The Context directory within sources repository which will be used during build
CONTEXT_DIR=${CONTEXT_DIR:-'java/quarkus'}
# The fully qualified image name e.g. docker.io/foo/bar:v1.0
DESTINATION_IMAGE_NAME=${DESTINATION_IMAGE_NAME:-'quay.io/rhdevelopers/knative-eventing-greeter:quarkus'}
----
copyToClipboard::copy-set-env[]

[#eventing-source-env]
[source,bash,subs="+macros,+attributes",linenums]
----
source ./setenv.sh
----
copyToClipboard::eventing-source-env[]

endif::[]

[#eventing-watch-logs]
== Watching Logs

:kube-svc: event-greeter
include::partial$watching-logs.adoc[]

The logs will have the output like below printing every minute.

[source]
----
INFO  [com.red.dev.dem.GreetingService] (XNIO-1 task-1) Event Message Received
event-greeter-g94kp-deployment-89f66cb58-wjl2v user-container  {
event-greeter-g94kp-deployment-89f66cb58-wjl2v user-container   "message" : "Thanks for doing Knative Tutorial",
event-greeter-g94kp-deployment-89f66cb58-wjl2v user-container   "host" : "Event  greeter => 'event-greeter-5cbh5-pod-52d8fb' : 1",
event-greeter-g94kp-deployment-89f66cb58-wjl2v user-container   "time" : "13:50:07"
event-greeter-g94kp-deployment-89f66cb58-wjl2v user-container }
----
[.text-center]
(OR)
[source]
----
INFO  [com.red.dev.dem.GreetingService] (XNIO-1 task-1) Event Message Received
event-greeter-g94kp-deployment-89f66cb58-wjl2v user-container  {
event-greeter-g94kp-deployment-89f66cb58-wjl2v user-container   "message" : "Thanks for doing Knative Tutorial",
event-greeter-g94kp-deployment-89f66cb58-wjl2v user-container   "host" : "Event  greeter => 'event-greeter-5cbh5-pod-52d8fb' : 2",
event-greeter-g94kp-deployment-89f66cb58-wjl2v user-container   "time" : "13:51:00"
event-greeter-g94kp-deployment-89f66cb58-wjl2v user-container }
----