= Eventing Source to Service
include::_attributes.adoc[]

[#eventing-source]
== Event Source

The event source listens to external events e.g. a kafka topic or for a file on a FTP server. It is responsible to drain the received event(s) along with its data to a configured https://en.wikipedia.org/wiki/Sink_(computing)[sink].

Navigate to the tutorial chapter's `knative` folder:

[source,bash,subs="+macros,+attributes"]
----
cd $TUTORIAL_HOME/05-eventing/knative
----

[#eventing-create-event-source]
=== Create Event Source
[.text-center]
.link:{github-repo}/{eventing-repo}/knative/event-source-svc.yaml[event-source-svc.yaml]
[source,yaml,linenums]
----
apiVersion: sources.eventing.knative.dev/v1alpha1
kind: CronJobSource #<1>
metadata:
  name: event-greeter-cronjob-source
spec:
  schedule: "* * * * *"
  data: '{"message": "Thanks for doing the Knative Tutorial"}'
  sink: 
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: event-greeter #<2>
----

<1> The type of event source, the eventing system deploys a bunch of sources out of the box and it also provides way to deploy custom resources
<2> The service(sink) where the event data will be sent

[NOTE]
====
Event Source can define the attributes that it wishes to receive via the 
spec.  In the above example it defines **schedule**(the the cron expression) and **data** that will be sent as part of the event.

When you xref:06-eventing/eventing.adoc#eventing-watch-logs[watch logs], you will notice this data being delivered to the service.
====

Run the following commands to create the event source resources:

[source,bash,subs="+macros,+attributes"]
----
kubectl apply -n knativetutorial -f link:{github-repo}/{eventing-repo}/knative/event-source-svc.yaml[event-source-svc.yaml]
----

.(OR)

[source,bash,subs="+macros,+attributes"]
----
oc apply -n knativetutorial -f link:{github-repo}/{eventing-repo}/knative/event-source-svc.yaml[event-source-svc.yaml] 
----

[#eventing-verify-event-source]
==== Verification

[source,bash,subs="+macros,+attributes"]
----
kubectl -n knativetutorial get cronjobsources.sources.eventing.knative.dev 
----

.(OR)

[source,bash,subs="+macros,+attributes"]
----
oc -n knativetutorial get cronjobsources.sources.eventing.knative.dev 
----
Running  the above command should return the following result:

[source,bash,subs="+macros,+attributes"]
----
NAME                       AGE
event-greeter-cronjob-source  39s
----

The conronjobsource also creates a service pod,

[source,bash,subs="+macros,+attributes"]
----
kubectl -n knativetutorial get pods 
----

.(OR)

[source,bash,subs="+macros,+attributes"]
----
oc -n knativetutorial get pods 
----

The above command will return an output like,

[source,bash,subs="+macros,+attributes"]
----
NAME                                                          READY     STATUS    RESTARTS   AGE
cronjob-event-greeter-cronjob-source-4v9vq-6bff96b58f-tgrhj   2/2       Running   0          6m
----

[#eventing-sink-service]
== Create Sink Service 

[#eventing-gen-sink-service]
=== Generate Sink Service

Navigate to tutorial chapter's `templates` folder:

[source,bash,subs="+macros,+attributes"]
----
cd $TUTORIAL_HOME/05-eventing/knative/templates
----

Run the following command to create the knative service that will be used as the subscriber for the cron events:

[source,bash,subs="+macros,+attributes",linenums]
----

jsonnet --ext-str image='<your-docker-image-name>' \
   link:{github-repo}/{eventing-repo}/knative/templates/service.jsonnet[service.jsonnet]\
   | yq r - | tee ../service.yaml
----

(e.g)
[source,bash,subs="+macros,+attributes",linenums]
----
jsonnet --ext-str image='docker.io/demo/event-greeter:0.0.1' \
   link:{github-repo}/{eventing-repo}/knative/templates/service.jsonnet[service.jsonnet] \
    | yq r - | tee ../service.yaml
----

[.text-center]
.service.yaml
[source,yaml,linenums]
----
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: event-greeter
spec:
  runLatest:
    configuration:
      revisionTemplate:
        metadata:
          labels:
            app: event-greeter
        spec:
          container:
            image: docker.io/demo/event-greeter:0.0.1 <1>
----

<1> Set from `image` parameter --  the fully qualified container image that will be pushed to the registry as part of the build --

[NOTE]
====
If you have skipped the xref:ROOT:05-build/build.adoc[Build] or xref:ROOT:05-build/build-templates.adoc[Build Templates] do not have the container image of `event-greeter`; then you can update the Knative serving service to use the pre-built event-greeter image available at `quay.io/rhdevelopers/knative-tutorial-event-greeter:0.0.1`
====

[#eventing-deploy-sink-service]
=== Deploy Sink Service

Navigate to tutorial chapter's `knative` folder:

[source,bash,subs="+macros,+attributes"]
----
cd $TUTORIAL_HOME/05-eventing/knative
----

Run the following commands to create the service:

[source,bash,subs="+macros,+attributes"]
----
kubectl apply -n knativetutorial -f service.yaml 
----

.(OR)

[source,bash,subs="+macros,+attributes"]
----
oc apply -n knativetutorial -f service.yaml 
----

You can xref:06-eventing/eventing.adoc#eventing-watch-logs[watch logs] to see the cron job source sending an event every 1 minute.

[#eventing-see-what-you-have-deployed]
=== See what you have deployed

==== sources
include::partial$knative-objects.adoc[tag=knative-event-cronjob-sources]

==== services
include::partial$knative-objects.adoc[tag=knative-event-services]

[#eventing-cleanup]
== Cleanup

[source,bash,subs="+macros,+attributes",linenums]
----
kubectl -n knativetutorial delete services.serving.knative.dev event-greeter
kubectl -n knativetutorial delete \
 cronjobsources.sources.eventing.knative.dev  event-greeter-cronjob-source
----

.(OR)

[source,bash,subs="+macros,+attributes",linenums]
----
oc -n knativetutorial delete services.serving.knative.dev event-greeter
oc -n knativetutorial delete \
 cronjobsources.sources.eventing.knative.dev  event-greeter-cronjob-source
----

NOTE: You can also delete xref:ROOT:05-build/build.adoc#build-apply-prereq-resources[pre-req resources] that were created if you dont need them any more.
