apiVersion: v1
kind: ServiceAccount
metadata:
  name: tutorial-tools
  namespace: che
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tutorial-tools-binding
  namespace: che
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: tutorial-tools
  namespace: che
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tutorial-tools-kubeconfig
  namespace: che
data:
  config: |
    apiVersion: v1
    kind: Config
    preferences: {}
    clusters:
    - cluster:
      name: knativetutorial
    users:
    - name: tutorial-tools
    contexts: []